// Africa and Asia. Every endpoint and field name below was verified against a live
// response on 2026-10-06. None of these agencies states a licence: query live, don't
// republish extracts.

import { msToIso, dmyToIso, num, looseNum, geomFirst } from "./normalize.js";

const nz = (v) => num(v, { zeroIsNull: true });

export const AFRICA_ASIA_SOURCES = [
  {
    key: "ID-MIGAS",
    country: "ID",
    state: null,
    label: "Indonesia oil & gas wells",
    probe: { well_name: "Minas" },
    agency: "Directorate General of Oil and Gas (Ditjen Migas), Ministry of Energy and Mineral Resources - MDR",
    url: "https://datamigas.esdm.go.id/arcgis/rest/services/MDR2/well/MapServer/0",
    pageMax: 1000,
    noPaging: true, // server 400s on resultOffset/resultRecordCount
    idKind: "id",
    idLabel: "UWI",
    extent: [94.0, -11.5, 141.5, 6.5],
    caveat: "No licence stated, and Ditjen Migas sells data downloads: query live, don't republish. operator is the operator's short name (BA_LN). Placeholder spud dates (00/00/0000) come back as null.",
    searchFields: {
      api: "UWI",
      well_name: "WELL_NAME",
      operator: "BA_LN",
      field: "FIELD_NAME",
      status: "STTS_TYPE",
      well_type: "WELL_CLASS",
    },
    normalize: (a, g) => ({
      api: a.UWI,
      wellName: a.WELL_NAME,
      alias: a.ALIAS_LN || null,
      operator: a.BA_LN,
      status: a.STTS_TYPE,
      wellType: a.WELL_CLASS,
      field: a.FIELD_NAME,
      workingArea: a.AREA_ID,
      environment: a.ENVRMT_TYP,
      ...geomFirst(a, g, "LAT", "LONG"),
      spudDate: dmyToIso(a.SPUD_DATE),
    }),
  },
  {
    key: "ZA-PASA",
    country: "ZA",
    state: null,
    label: "South Africa petroleum wells (mostly offshore: Bredasdorp, Orange...)",
    probe: { county: "Bredasdorp" },
    agency: "Petroleum Agency SA (PASA)",
    url: "https://geoportal.petroleumagencysa.com/arcgis/rest/services/Storefront/Quick_Find/MapServer/0",
    pageMax: 1000,
    idKind: "id",
    idLabel: "UWI",
    extent: [10.0, -38.0, 35.0, -22.0],
    caveat: "PASA's website reserves all rights: query live, don't republish. county filters by basin. Depths in metres.",
    searchFields: {
      api: "uwi",
      well_name: "Well_name",
      operator: "Operator",
      county: "Basin",
      field: "Block",
      status: "crstatus",
      well_type: "Well_type",
    },
    normalize: (a, g) => ({
      api: a.uwi,
      wellName: a.Well_name,
      operator: a.Operator,
      licensee: a.Licensee,
      status: a.crstatus,
      wellType: a.Well_type,
      hydrocarbonStatus: a.HC_status,
      field: a.Block,
      county: a.Basin,
      ...geomFirst(a, g),
      spudDate: dmyToIso(a.Spud_date),
      rigReleaseDate: dmyToIso(a.Rigrel),
      depthMD: nz(a.Depth_md) ?? nz(a.Drillers_TD),
      depthTVD: nz(a.TVD),
      waterDepth: nz(a.Water_dept),
    }),
  },
  {
    key: "MZ-INP",
    country: "MZ",
    state: null,
    label: "Mozambique exploration & production wells",
    probe: { operator: "Sasol" },
    agency: "Instituto Nacional de Petróleo (INP)",
    url: "https://services3.arcgis.com/GwpN7CU0VUHlIXMI/arcgis/rest/services/Actividades_de_Pesquisa/FeatureServer/0",
    pageMax: 1000,
    idKind: "id",
    idLabel: "short well name (e.g. 'P-25')",
    extent: [30.0, -27.0, 45.0, -10.0],
    caveat: "Published from an INP staff ArcGIS Online account; no licence stated.",
    searchFields: {
      api: "Well_short",
      well_name: "Well_long",
      operator: "Long_name",
      field: "Concession",
      well_type: "Well_kind",
    },
    normalize: (a, g) => ({
      api: a.Well_short,
      wellName: a.Well_long,
      operator: a.Long_name,
      status: null,
      wellType: a.Well_kind,
      content: a.Well_conte,
      discovery: a.Discovery,
      field: a.Concession,
      ...geomFirst(a, g),
      spudDate: msToIso(a.Spud_date),
      completionDate: msToIso(a.Completion),
    }),
  },
  {
    key: "KE-PET",
    country: "KE",
    state: null,
    label: "Kenya petroleum exploration wells (unofficial copy of the ministry map)",
    probe: { well_name: "Ngamia" },
    agency: "State Department for Petroleum map, re-hosted on ArcGIS Online by a third-party account",
    url: "https://services1.arcgis.com/IQkrFigagkCSClLX/arcgis/rest/services/Kenya_Upstream_Petroleum_Exploration_Map_WFL1/FeatureServer/0",
    pageMax: 2000,
    idKind: "id",
    idLabel: "map well id",
    apiNumeric: true,
    extent: [33.8, -4.8, 42.0, 5.1],
    caveat:
      "Unofficial: an ArcGIS Online copy of the State Department for Petroleum's upstream exploration map (December 2024), not published by the ministry itself; no licence stated. Exploration, appraisal and stratigraphic wells (Lokichar/Turkana, Lamu, Anza, Mandera); no geothermal wells. Depths in metres below rotary table.",
    searchFields: {
      api: "KEID_Wells",
      well_name: "WELL_NAME",
      operator: "OPERATOR",
      field: "Basin",
      status: "Well_Statu",
      well_type: "Well_Type",
    },
    normalize: (a, g) => ({
      api: a.KEID_Wells != null ? String(a.KEID_Wells) : null,
      wellName: a.WELL_NAME,
      operator: a.OPERATOR,
      status: a.Well_Statu,
      wellType: a.Well_Type,
      content: a.Well_Conte,
      field: a.Basin?.replace(/\s+/g, " ") ?? null,
      prospect: a.PROSPECT_N,
      ...geomFirst(a, g, "Latitude", "Longitude"),
      spudDate: msToIso(a.SPUD_DATE),
      completionDate: msToIso(a.Completion),
      depthMD: nz(a.TMD_MDRT),
      depthTVD: nz(a.TVD_TVDRT),
      waterDepth: looseNum(a.WaterDepth),
      rig: a.Rig_Name,
      comment: a.COMMENT,
    }),
  },
];
