// Canada, Latin America and the Caribbean. Every endpoint and field name below was
// verified against a live response on 2026-10-06.

import { msToIso, isoDate, dmyToIso, namedDateToIso, num, looseNum, geomFirst, centroid } from "./normalize.js";

const nz = (v) => num(v, { zeroIsNull: true });

// Saskatchewan's vertical and non-vertical layers share one schema.
function saskatchewan({ key, layer, label, probe, extraCaveat }) {
  return {
    key,
    country: "CA",
    state: "SK",
    label,
    probe,
    agency: "Saskatchewan Ministry of Energy and Resources",
    url: `https://gis.saskatchewan.ca/arcgis/rest/services/Economy/Petroleum/MapServer/${layer}`,
    pageMax: 2000,
    idKind: "id",
    idLabel: "wellbore UWI",
    dedupeBy: "WELL_CWI", // one row per wellbore completion
    extent: [-110.1, 48.9, -101.3, 60.1],
    caveat: `Updated daily. One record per well (completions de-duplicated); status/type/pool describe the first completion returned. ${extraCaveat}`,
    searchFields: {
      api: "WELLBORE_UWI",
      well_name: "LEGACYWELLNAME",
      operator: "WELLLICENCEBUSINESSASSOCIATE",
      county: "RURALMUNICIPALITY",
      field: "COMPLETIONPOOL",
      status: "WELLSTATUS",
      well_type: "WELLBORECOMP_CURRENTCOMPTYPE",
    },
    normalize: (a, g) => {
      const c = centroid(g);
      return {
        api: a.WELLBORE_UWI,
        wellId: a.WELL_CWI,
        wellName: a.LEGACYWELLNAME,
        operator: a.WELLLICENCEBUSINESSASSOCIATE,
        status: a.WELLSTATUS,
        wellType: a.WELLBORECOMP_CURRENTCOMPTYPE,
        laheeClass: a.WELLLAHEECLASSIFICATION,
        trajectory: a.WELLDRILLINGTRAJECTORY,
        field: a.COMPLETIONPOOL,
        formations: a.COMPLETIONFORMATIONS,
        county: a.RURALMUNICIPALITY,
        area: a.SURFACEGEOAREA,
        // surface location (the geometry of a non-vertical well is its whole path)
        latitude: nz(a.SURFACELATITUDE) ?? c?.y ?? null,
        longitude: nz(a.SURFACELONGITUDE) ?? c?.x ?? null,
        licenceDate: msToIso(a.WELLLICENCEISSUEDATE),
        spudDate: msToIso(a.WELLDERIVEDSPUDDATE),
        endDrillDate: msToIso(a.WELLFINISHDRILLDATE),
        abandonDate: msToIso(a.WELLABANDONEDDATE),
        onProductionDate: msToIso(a.ONPRODUCTIONDATE),
        depthMD: looseNum(a.WELLBORE_BH_MEASUREDDEPTH),
        depthTVD: looseNum(a.WELLBORE_BH_TRUEVERTICALDEPTH),
        depthUnit: "m",
        licence: a.WELLLICENCENUMBER,
      };
    },
  };
}

export const AMERICAS_SOURCES = [
  // ---------------------------------------------------------------- Canada
  saskatchewan({
    key: "SK",
    layer: 0,
    label: "Saskatchewan oil & gas wells (vertical)",
    probe: { operator: "Whitecap" },
    extraCaveat: "Horizontal and directional wells are in SK-HZ.",
  }),
  saskatchewan({
    key: "SK-HZ",
    layer: 1,
    label: "Saskatchewan oil & gas wells (horizontal / directional)",
    probe: { operator: "Whitecap" },
    extraCaveat: "Vertical wells are in SK.",
  }),
  {
    key: "BC",
    country: "CA",
    state: "BC",
    label: "British Columbia oil & gas wells",
    probe: { well_name: "Tourmaline" },
    agency: "BC Energy Regulator (BCER)",
    url: "https://geoweb-ags.bc-er.ca/arcgis/rest/services/WELL/WELL_BOTTOM_HOLE_STATE_PT/FeatureServer/0",
    pageMax: 2000,
    idKind: "id",
    idLabel: "UWI",
    extent: [-139.1, 48.2, -114.0, 60.1],
    caveat: "Bottom-hole locations. operator is BCER's operator abbreviation; no spud date or depth in this layer.",
    searchFields: {
      api: "UNIQUE_WELL_IDENTIFIER",
      well_name: "WELL_NAME",
      operator: "OPERATOR_ABBREVIATION",
      field: "WELL_AREA_NAME",
      status: "WELL_ACTIVITY",
      well_type: "BORE_FLUID_TYPE",
    },
    normalize: (a, g) => ({
      api: a.UNIQUE_WELL_IDENTIFIER,
      wellAuthority: a.WELL_AUTHORITY_NUMBER,
      wellName: a.WELL_NAME,
      operator: a.OPERATOR_ABBREVIATION,
      status: a.WELL_ACTIVITY,
      wellType: a.BORE_FLUID_TYPE,
      operationType: a.OPERATION_TYPE,
      field: a.WELL_AREA_NAME,
      ...geomFirst(a, g),
      statusDate: msToIso(a.STATUS_EFFECTIVE_DATE),
      confidential: a.CONFIDENTIAL_FLAG,
    }),
  },
  {
    key: "ON",
    country: "CA",
    state: "ON",
    label: "Ontario oil, gas, salt & storage wells (incl. Lake Erie)",
    probe: { operator: "Enbridge" },
    agency: "Ontario Ministry of Natural Resources (Land Information Ontario)",
    url: "https://ws.lioservices.lrc.gov.on.ca/arcgis2/rest/services/LIO_OPEN_DATA/LIO_Open08/MapServer/22",
    pageMax: 2000,
    idKind: "id",
    idLabel: "Ontario well id",
    extent: [-83.6, 41.6, -74.3, 46.5],
    license: "Open Government Licence - Ontario",
    searchFields: {
      api: "WELL_ID",
      well_name: "WELL_NAME",
      operator: "OPERATOR",
      county: "COUNTY",
      status: "WELL_MODE",
      well_type: "WELL_TYPE",
    },
    normalize: (a, g) => ({
      api: a.WELL_ID,
      licence: a.LICENCE_NUMBER,
      wellName: a.WELL_NAME,
      operator: a.OPERATOR,
      status: a.WELL_MODE,
      wellType: a.WELL_TYPE,
      county: a.COUNTY,
      township: a.TOWNSHIP,
      ...geomFirst(a, g, "SURFACE_LATITUDE_83", "SURFACE_LONGITUDE_83"),
      spudDate: msToIso(a.SPUD_DATE),
      tdReachedDate: msToIso(a.TOTAL_DEPTH_REACHED_DATE),
      plugDate: msToIso(a.PLUGGING_END_DATE),
      depthMD: nz(a.TOTAL_DEPTH),
      depthTVD: nz(a.TRUE_VERTICAL_DEPTH),
      offshoreBlock: a.OFFSHORE_BLOCK,
    }),
  },
  {
    key: "NL-OFF",
    country: "CA",
    state: "NL",
    label: "Newfoundland & Labrador offshore wells",
    probe: { operator: "Exxon" },
    agency: "Newfoundland and Labrador Department of Industry, Energy and Technology",
    url: "https://services8.arcgis.com/jSziFsB3BeiveI9A/arcgis/rest/services/NL_Petro_Well/FeatureServer/106",
    pageMax: 2000,
    idKind: "id",
    idLabel: "UWI",
    extent: [-67.0, 40.0, -42.0, 61.0],
    caveat: "Includes re-entries as separate records. Depths in metres.",
    searchFields: {
      api: "Unique_Wel",
      well_name: "Well_Name",
      operator: "Operator",
      field: "Area",
      status: "Well_Statu",
      well_type: "Classifica",
    },
    normalize: (a, g) => ({
      api: a.Unique_Wel,
      wellName: a.Well_Name,
      operator: a.Operator,
      status: a.Well_Statu,
      wellType: a.Classifica,
      field: a.Area,
      landTenure: a.Land_Tenur,
      ...geomFirst(a, g, "LATDDddddd", "LNGDDddddd"),
      spudDate: msToIso(a.Spud_Date1),
      endDate: msToIso(a.Well_Ter_1),
      depthMD: nz(a.Total_Dept),
      waterDepth: nz(a.Water_Dept),
      inventoryUrl: a.Well_Inv,
      summaryUrl: a.WellSum,
    }),
  },
  {
    key: "NS-OFF",
    country: "CA",
    state: "NS",
    label: "Nova Scotia offshore wells",
    probe: { operator: "Shell" },
    agency: "Canada-Nova Scotia Offshore Energy Board directory (via NRCan)",
    url: "https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/Nova_Scotia_Offshore_Petroleum_en/MapServer/0",
    pageMax: 2000,
    idKind: "id",
    idLabel: "well name",
    extent: [-67.0, 41.0, -56.0, 47.5],
    license: "Open Government Licence - Canada",
    caveat: "The regulator's 2022 directory of wells.",
    searchFields: {
      api: "Well_Name",
      well_name: "Well_Name",
      operator: "Company",
      well_type: "Well_Type",
    },
    normalize: (a, g) => ({
      api: a.Well_Name,
      wellName: a.Well_Name,
      operator: a.Company,
      status: null,
      wellType: a.Well_Type,
      ...geomFirst(a, g, "latitude_d", "longitud_1"),
      spudDate: namedDateToIso(a.Spud_Date),
      endDate: namedDateToIso(a.Well_Termi),
      depthMD: nz(a.Total_Dept),
      waterDepth: nz(a.Water_Dept),
      rig: a.Drilling_U,
    }),
  },
  {
    key: "NT",
    country: "CA",
    state: "NT",
    label: "Northwest Territories oil & gas wells",
    probe: { operator: "Imperial" },
    agency: "NWT Office of the Regulator of Oil and Gas Operations (OROGO)",
    url: "https://www.apps.geomatics.gov.nt.ca/arcgis/rest/services/GNWT/Economy_LCC/MapServer/27",
    pageMax: 1500,
    idKind: "id",
    idLabel: "UWI",
    extent: [-136.5, 59.9, -101.9, 79.0],
    searchFields: {
      api: "UWI",
      well_name: "Well_Name",
      operator: "Last_Operator",
      county: "Region",
      status: "Well_Status",
      well_type: "Classification",
    },
    normalize: (a, g) => ({
      api: a.UWI,
      wellName: a.Well_Name,
      operator: a.Last_Operator,
      owner: a.Current_Owner,
      status: a.Well_Status,
      wellType: a.Classification,
      county: a.Region,
      ...geomFirst(a, g, "NAD_83_Lat", "NAD_83_Long"),
      spudDate: msToIso(a.Last_SPUD_Date),
      rigReleaseDate: msToIso(a.Last_Rig_Release_Date),
      firstSpudYear: a.First_SPUD_year,
    }),
  },
  {
    key: "YT",
    country: "CA",
    state: "YT",
    label: "Yukon oil & gas wells",
    probe: { field: "Eagle Plain" },
    agency: "Government of Yukon (Oil and Gas Resources Branch)",
    url: "https://mapservices.gov.yk.ca/arcgis/rest/services/GeoYukon/GY_OilGas/MapServer/0",
    pageMax: 1000,
    idKind: "id",
    idLabel: "UWI",
    extent: [-141.1, 59.9, -123.8, 69.7],
    searchFields: {
      api: "WELL_UWI",
      well_name: "WELL_NAME",
      operator: "WELL_LICENSEE",
      field: "SEDIMENT_BASIN_NAME",
      status: "WELL_STATUS",
      well_type: "WELL_TYPE",
    },
    normalize: (a, g) => ({
      api: a.WELL_UWI,
      wellName: a.WELL_NAME,
      operator: a.WELL_LICENSEE,
      status: a.WELL_STATUS,
      wellType: a.WELL_TYPE,
      classification: a.WELL_CLASSIFICATION,
      field: a.SEDIMENT_BASIN_NAME,
      ...geomFirst(a, g, "LATITUDE_DD", "LONGITUDE_DD"),
      licensedDate: msToIso(a.LICENSED_DATE),
      firstProductionDate: msToIso(a.FIRST_PRODUCTION_DATE),
      abandonDate: msToIso(a.ABANDONED_DATE),
    }),
  },
  {
    key: "YT-GEO",
    country: "CA",
    state: "YT",
    label: "Yukon geothermal boreholes (temperature, gradient, heat flow)",
    probe: { well_type: "Heat exchange" },
    agency: "Yukon Geological Survey",
    url: "https://mapservices.gov.yk.ca/arcgis/rest/services/GeoYukon/GY_Geological/MapServer/123",
    pageMax: 1000,
    idKind: "id",
    idLabel: "borehole name",
    extent: [-141.1, 59.9, -123.8, 69.7],
    caveat: "Boreholes with geothermal measurements (many are water wells). Temperatures in deg C, gradients in deg C/km, depths in metres.",
    searchFields: {
      api: "NAME",
      well_name: "NAME",
      field: "LOCATION",
      status: "STATUS",
      well_type: "PURPOSE",
    },
    normalize: (a, g) => ({
      api: a.NAME,
      wellName: a.NAME,
      operator: null,
      status: a.STATUS,
      wellType: a.PURPOSE,
      field: a.LOCATION,
      ...geomFirst(a, g, "LATITUDE_DD", "LONGITUDE_DD"),
      depth: nz(a.DRILL_DEPTH),
      waterTempC: num(a.TEMP_WATER),
      maxTempC: num(a.TEMP_MAX),
      thermalGradient: num(a.THERM_GRAD),
      heatFlow: num(a.HEAT_FLOW),
      thermalConductivity: num(a.THERM_COND),
      reference: a.REFERENCE,
    }),
  },

  // ----------------------------------------------- Central America & Caribbean
  {
    key: "BZ",
    country: "BZ",
    state: null,
    label: "Belize exploration & production wells (onshore and offshore)",
    probe: { operator: "Belize Natural" },
    agency: "Government of Belize - petroleum data coverage map (Geology & Petroleum Department data)",
    url: "https://services9.arcgis.com/t72FqAnywZcQihL0/arcgis/rest/services/Belize_Petroleum_Data_Coverage_Map_WFL1/FeatureServer/1",
    pageMax: 2000,
    idKind: "id",
    idLabel: "well abbreviation (e.g. 'MU #4')",
    extent: [-89.3, 15.8, -86.9, 18.6],
    caveat: "Published on a Government of Belize ArcGIS Online map, last edited November 2024. Total depth units are not stated (values suggest feet). dataAccess says whether the well's data package is public.",
    searchFields: {
      api: "Well_Abbre",
      well_name: "Well_Name",
      operator: "Company",
      field: "Location",
      status: "Status",
    },
    normalize: (a, g) => ({
      api: a.Well_Abbre,
      wellName: a.Well_Name,
      operator: a.Company,
      status: a.Status,
      result: a.Results,
      wellType: null,
      field: a.Location,
      ...geomFirst(a, g),
      spudDate: msToIso(a.Spud_Date),
      completionDate: msToIso(a.Competion_),
      depthMD: nz(a.TD),
      formationAtTd: a.Geological,
      ageAtTd: a.Age_at_TD,
      dataAccess: a.Data_Acces,
    }),
  },
  {
    key: "MX",
    country: "MX",
    state: null,
    label: "Mexico oil & gas wells (onshore and offshore)",
    probe: { field: "Akal" },
    agency: "CNH well inventory as re-hosted by SEMARNAT",
    url: "https://geomaticasig1.semarnat.gob.mx/arcgis/rest/services/Hosted/Pozos_2024/FeatureServer/0",
    pageMax: 2000,
    idKind: "id",
    idLabel: "well name",
    extent: [-118.5, 14.4, -86.5, 32.8],
    caveat: "A 2024 snapshot (copyright PEMEX): wells drilled since are missing, and there is no operator field.",
    searchFields: {
      api: "pozo",
      well_name: "pozo",
      field: "campo",
      county: "entidad",
      status: "estado_act",
      well_type: "clasificac",
    },
    normalize: (a, g) => ({
      api: a.pozo,
      wellName: a.pozo,
      operator: null,
      status: a.estado_act,
      wellType: a.clasificac,
      hydrocarbon: a.tipo_de_hi,
      field: a.campo,
      county: a.entidad,
      location: a.ubicacin,
      ...geomFirst(a, g),
      spudDate: namedDateToIso(a.fecha_inic),
      endDate: namedDateToIso(a.fecha_fin_),
      depthMD: nz(a.profundida),
      trajectory: a.trayectori,
    }),
  },

  // ---------------------------------------------------------- South America
  {
    key: "CO-EPIS",
    country: "CO",
    state: null,
    label: "Colombia oil & gas wells",
    probe: { operator: "Ecopetrol" },
    agency: "Servicio Geológico Colombiano (EPIS)",
    url: "https://srvags.sgc.gov.co/arcgis/rest/services/EPIS/EPIS_V2/MapServer/0",
    pageMax: 2000,
    noPaging: true, // server 400s on resultOffset/resultRecordCount
    idKind: "id",
    idLabel: "UWI",
    extent: [-79.5, -4.3, -66.8, 13.5],
    caveat: "Updated continuously (FECHA_ACTU). Some class/status values are placeholders ('0', blank).",
    searchFields: {
      api: "UWI",
      well_name: "WELL_NAME",
      operator: "OPERATOR_W",
      county: "DEPARTAMEN",
      field: "FIELD_ABRE",
      status: "WELL_STA_1",
      well_type: "WELL_CLA_1",
    },
    normalize: (a, g) => ({
      api: a.UWI,
      wellName: a.WELL_NAME,
      operator: a.OPERATOR_W || a.COMPANY_CO,
      status: a.WELL_STA_1,
      wellType: a.WELL_CLA_1,
      welltype2: a.WELLTYPE,
      field: a.FIELD_ABRE,
      basin: a.GEOLOGIC_P,
      county: a.DEPARTAMEN,
      municipality: a.WELL_COU_1,
      contract: a.CONTRATO,
      ...geomFirst(a, g, "WELL_LATIT", "WELL_LONGI"),
      spudDate: msToIso(a.WELL_SPUD_),
      completionDate: msToIso(a.WELL_COMPL),
      depthMD: nz(a.WELL_DRILL),
      depthTVD: nz(a.WELL_TVD),
      updatedDate: msToIso(a.FECHA_ACTU),
    }),
  },
  {
    key: "BR-ANP",
    country: "BR",
    state: null,
    kind: "wfs",
    label: "Brazil oil & gas wells (onshore and offshore, incl. pre-salt)",
    probe: { operator: "Equinor" },
    agency: "ANP - Agência Nacional do Petróleo, Gás Natural e Biocombustíveis",
    url: "https://geomaps.anp.gov.br/geoserver/ows",
    typeName: "sisroc:pocos_gishub_db",
    geometryName: "SHAPE",
    sortBy: "feicao_id",
    pageMax: 2000,
    idKind: "id",
    idLabel: "ANP well register number (cadastro)",
    extent: [-74.0, -34.0, -28.0, 5.5],
    caveat: "Refreshed daily. Depths in metres. ambiente T = onshore, M = offshore.",
    searchFields: {
      api: "cadastro",
      well_name: "name",
      operator: "operador",
      county: "sigla_estado",
      field: "nome_campo",
      status: "situacao",
      well_type: "categoria",
    },
    normalize: (a, g) => ({
      api: a.cadastro,
      wellName: a.name,
      operator: a.operador,
      status: a.situacao,
      wellType: a.categoria,
      purpose: a.tipo,
      reclassification: a.reclassificacao,
      field: a.nome_campo,
      basin: a.nome_bacia,
      block: a.nome_bloco,
      county: a.sigla_estado,
      offshore: a.ambiente === "M" ? true : a.ambiente === "T" ? false : null,
      ...geomFirst(a, g, "latitude", "longitude"),
      spudDate: dmyToIso(a.dat_inicio),
      endDrillDate: dmyToIso(a.dat_termin),
      completionDate: dmyToIso(a.dat_conclusao),
      depthMD: nz(a.prof_medid),
      depthTVD: nz(a.prof_vert),
      waterDepth: nz(a.lamina_dagua),
      direction: a.direcao,
      rig: a.nome_sonda,
      preSalt: a.at_presal,
    }),
  },
  {
    key: "PE",
    country: "PE",
    state: null,
    kind: "wfs",
    label: "Peru oil & gas wells",
    probe: { operator: "Pluspetrol" },
    agency: "PERUPETRO",
    url: "https://geoportal.perupetro.com.pe/geoserver/ows",
    typeName: "cartografia_pp:Pozos",
    geometryName: "geom",
    sortBy: "uwi",
    pageMax: 2000,
    idKind: "id",
    idLabel: "UWI",
    extent: [-81.5, -18.5, -68.5, 0.1],
    caveat: "estado holds PERUPETRO status codes; des_estado (status here) is the description.",
    searchFields: {
      api: "uwi",
      well_name: "nombre",
      operator: "cia_operad",
      county: "region",
      field: "yacimiento",
      status: "des_estado",
      well_type: "tipo",
    },
    normalize: (a, g) => ({
      api: a.uwi,
      wellName: a.nombre,
      alias: a.alias,
      operator: a.cia_operad,
      status: a.des_estado ?? a.estado,
      condition: a.condicion,
      wellType: a.tipo,
      field: a.yacimiento,
      basin: a.cuenca,
      county: a.region,
      ...geomFirst(a, g, "latitud", "longitud"),
      spudDate: isoDate(a.f_inicial),
      endDate: isoDate(a.f_final),
    }),
  },
  ...[
    ["AR-CONV", "ms:pozos_convencionales", "Argentina oil & gas wells - conventional"],
    ["AR-SHALE", "ms:pozos_noconvencionales_shale", "Argentina oil & gas wells - shale (Vaca Muerta...)"],
    ["AR-TIGHT", "ms:pozos_noconvencionales_tight", "Argentina oil & gas wells - tight"],
    ["AR-OTHER", "ms:pozos_noinformados", "Argentina oil & gas wells - resource type not reported"],
  ].map(([key, typeName, label]) => ({
    key,
    country: "AR",
    state: null,
    kind: "wfs",
    dialect: "fes", // MapServer
    label,
    probe: { operator: "YPF" },
    agency: "Secretaría de Energía de la Nación (Argentina)",
    url: "https://sig.energia.gob.ar/wmspubmap",
    typeName,
    geometryName: "msGeometry",
    pageMax: 1000,
    idKind: "id",
    idLabel: "well code (sigla, e.g. 'YPF.Nq.BP.x-2')",
    extent: [-73.6, -55.1, -53.6, -21.7],
    license: "Secretaría de Energía open data (published as CC BY 4.0 on datos.energia.gob.ar)",
    caveat: "Argentina's well list is split by resource type across AR-CONV, AR-SHALE, AR-TIGHT and AR-OTHER; search with country=AR to query all four. Depths in metres.",
    searchFields: {
      api: "sigla",
      well_name: "sigla",
      operator: "empresa",
      county: "provincia",
      field: "yacimiento",
      status: "tipoestado",
      well_type: "tipopozo",
    },
    normalize: (a, g) => ({
      api: a.sigla,
      wellId: a.idpozo,
      wellName: a.sigla,
      operator: a.empresa,
      status: a.tipoestado,
      wellType: a.tipopozo,
      classification: a.clasificacion,
      resourceType: [a.tipo_recurso, a.sub_tipo_recurso].filter(Boolean).join(" / ") || null,
      formation: a.formacion,
      field: a.yacimiento,
      concession: a.area,
      basin: a.cuenca,
      county: a.provincia,
      ...geomFirst(a, g),
      spudDate: isoDate(a.adjiv_fecha_inicio_perf),
      endDrillDate: isoDate(a.adjiv_fecha_fin_perf),
      completionDate: isoDate(a.adjiv_fecha_fin_term),
      depthMD: nz(a.profundidad_metros),
      extraction: a.tipoextraccion,
    }),
  })),
];
