// Europe, including overseas France. Every endpoint and field name below was verified
// against a live response on 2026-10-06.

import { msToIso, isoDate, dmyToIso, namedDateToIso, num, looseNum, geomFirst } from "./normalize.js";

const nz = (v) => num(v, { zeroIsNull: true });

// Orkustofnun's one-letter purpose codes (idtilgangur) for the common geothermal classes.
const ICELAND_PURPOSE = {
  G: "Steam production",
  H: "Hot water production",
  N: "Reinjection",
  T: "Temperature gradient",
  R: "Power plant research",
  A: "Other",
};

const ISLAND_BOXES = {
  metropole: [-5.3, 41.3, 9.7, 51.2],
  guadeloupe: [-61.9, 15.8, -60.9, 16.6],
  martinique: [-61.3, 14.3, -60.7, 14.9],
  guyane: [-54.7, 2.1, -51.5, 5.9],
  reunion: [55.2, -21.4, 55.9, -20.8],
  mayotte: [44.9, -13.1, 45.4, -12.6],
};

export const EUROPE_SOURCES = [
  {
    key: "FR-BSS",
    country: "FR",
    state: null,
    kind: "wfs",
    dialect: "fes", // MapServer: CQL_FILTER is silently ignored
    label: "France boreholes incl. overseas departments (Guadeloupe/Bouillante, Martinique, Réunion...)",
    probe: { county: "Bouillante" },
    agency: "BRGM - Banque du Sous-Sol (BSS)",
    url: "https://geoservices.brgm.fr/geologie",
    // geoservices.brgm.fr's HTTPS front end rejects some networks outright ("Request Rejected");
    // the same MapServer answers on plain HTTP.
    fallbackUrl: "http://geoservices.brgm.fr/geologie",
    typeName: "ms:BSS_TOTAL_SANS_LABEL",
    geometryName: "msGeometry",
    pageMax: 1000,
    idKind: "id",
    idLabel: "BSS id (e.g. BSS002NLFW)",
    extent: Object.values(ISLAND_BOXES),
    caveat:
      "A registry of every borehole (geothermal, water, mining, geotechnical...), not only deep wells. well_type matches the declared purpose ('geothermie'); county matches the commune. No operator or status fields. Each record links its InfoTerre detail sheet.",
    searchFields: {
      api: "bss_id",
      well_name: "designation",
      county: "nom_commune",
      well_type: "recherche",
    },
    normalize: (a, g) => ({
      api: a.bss_id,
      reference: a.reference,
      wellName: a.nom_local || a.designation || a.indice,
      operator: null,
      status: a.etat_ouvrage,
      wellType: a.recherche || a.utilisation || null,
      boreholeKind: a.nature,
      county: a.nom_commune,
      department: a.nom_departement,
      ...geomFirst(a, g, "latitude", "longitude"),
      completionDate: isoDate(a.date_realisation),
      depth: looseNum(a.prof_atteinte),
      depthUnit: "m",
      detailSheet: a.bss_id ? `http://ficheinfoterre.brgm.fr/InfoterreFiche/ficheBss.action?id=${a.bss_id}` : null,
    }),
  },
  {
    key: "NO-SODIR",
    country: "NO",
    state: null,
    label: "Norway offshore wellbores (all: exploration, development, other)",
    probe: { operator: "Equinor" },
    agency: "Sodir - Norwegian Offshore Directorate (FactMaps)",
    url: "https://factmaps.sodir.no/api/rest/services/Factmaps/FactMapsWGS84/FeatureServer/201",
    pageMax: 1000,
    idKind: "id",
    idLabel: "wellbore name (e.g. '15/9-19 A')",
    extent: [-2.0, 56.0, 38.0, 75.0],
    license: "Norwegian Licence for Open Government Data (NLOD)",
    caveat: "Synced daily. Depths in metres. Coordinates come from the geometry (the wlbNsDecDeg/wlbEwDecDeg attributes are ED50).",
    searchFields: {
      api: "wlbWellboreName",
      well_name: "wlbWell",
      operator: "wlbDrillingOperator",
      county: "wlbMainArea",
      field: "wlbField",
      status: "wlbStatus",
      well_type: "wlbPurpose",
    },
    normalize: (a, g) => ({
      api: a.wlbWellboreName,
      npdid: a.wlbNpdidWellbore,
      wellName: a.wlbWellboreName,
      well: a.wlbWell,
      operator: a.wlbDrillingOperator,
      status: a.wlbStatus,
      wellType: a.wlbWellType,
      purpose: a.wlbPurpose,
      content: a.wlbContent,
      field: a.wlbField,
      discovery: a.wlbDiscovery,
      county: a.wlbMainArea,
      licence: a.wlbProductionLicence,
      ...geomFirst(a, g),
      spudDate: msToIso(a.wlbEntryDate),
      completionDate: msToIso(a.wlbCompletionDate),
      depthMD: nz(a.wlbTotalDepth),
      depthTVD: nz(a.wlbFinalVerticalDepth),
      waterDepth: nz(a.wlbWaterDepth),
      bottomHoleTempC: nz(a.wlbBottomHoleTemperature),
      formationAtTd: a.wlbFormationAtTd,
      factPageUrl: a.wlbFactPageUrl,
    }),
  },
  ...[
    {
      key: "GB-NSTA-OFF",
      label: "UK offshore wellbores (UKCS)",
      url: "https://services-eu1.arcgis.com/OZMfUznmLTnWccBc/arcgis/rest/services/UKCS_offshore_wellbore_top_holes_(WGS84)/FeatureServer/0",
      operatorField: "TDOPERATOR",
      probe: { operator: "Harbour" },
      extent: [-12.0, 49.0, 4.0, 62.5],
    },
    {
      key: "GB-NSTA-ON",
      label: "England onshore petroleum wells",
      url: "https://services-eu1.arcgis.com/OZMfUznmLTnWccBc/arcgis/rest/services/UKCS%20onshore%20petroleum%20wells%20top%20holes%20WGS84/FeatureServer/0",
      operatorField: "SUBAREAOP", // TDOPERATOR is mostly 'No Data Available' onshore
      probe: { operator: "Cuadrilla" },
      extent: [-6.5, 49.8, 2.0, 56.0],
      onshore: true,
    },
  ].map((v) => ({
    key: v.key,
    country: "GB",
    state: null,
    label: v.label,
    probe: v.probe,
    agency: "North Sea Transition Authority (NSTA)",
    url: v.url,
    pageMax: 1000,
    idKind: "id",
    idLabel: "well registration number (e.g. '9/13a- 20B')",
    extent: v.extent,
    license: "NSTA Open User Licence",
    caveat: "Depths in metres (TVDSS = true vertical depth sub-sea). Coordinates come from the geometry (TOPHOLEXDD/YDD are ED50 strings).",
    searchFields: {
      api: "WELLREGNO",
      well_name: "NAME",
      operator: v.operatorField,
      field: "TARGETFLD",
      status: "WELLOPSTAT",
      well_type: "ORIGINTENT",
      ...(v.onshore ? { county: "ONS_COUNTY" } : {}),
    },
    normalize: (a, g) => ({
      api: a.WELLREGNO,
      wellName: a.NAME || a.WELLREGNO,
      operator: a[v.operatorField] || a.TDOPERATOR || null,
      status: a.WELLOPSTAT,
      completionStatus: a.COMPLESTAT,
      wellType: a.ORIGINTENT,
      currentIntent: a.CURRWELLIN,
      field: a.TARGETFLD,
      licence: a.LICNO,
      ...(v.onshore ? { county: a.ONS_COUNTY, unconventionalType: a.UNCWELTYP } : {}),
      ...geomFirst(a, g),
      spudDate: msToIso(a.SPUDDATE),
      completionDate: msToIso(a.COMPLEDATE),
      depthMD: nz(a.TDMDDEPM),
      depthTVDSS: nz(a.TDTVDSSM),
      waterDepth: nz(a.WATDEP_M),
      fluids: a.FLUIDTYPES,
      maxTempC: nz(a.MXTDTEMPC),
      deviation: a.DEVTYPE,
    }),
  })),
  {
    key: "GB-BGS",
    country: "GB",
    state: null,
    label: "Great Britain borehole index (all onshore drilling, incl. deep geothermal)",
    probe: { well_name: "geothermal" },
    agency: "British Geological Survey (Single Onshore Borehole Index)",
    url: "https://map.bgs.ac.uk/arcgis/rest/services/GeoIndex_Onshore/boreholes/MapServer/0",
    pageMax: 2000,
    idKind: "id",
    idLabel: "BGS borehole reference (e.g. SW74SW114)",
    extent: [-8.7, 49.8, 2.0, 61.0],
    caveat: "Over a million boreholes of every kind, with no operator, status or purpose: geothermal wells are only findable by name (e.g. 'United Downs', 'Eden') or location. depth -1 means unknown.",
    searchFields: {
      api: "REFERENCE",
      well_name: "NAME",
    },
    normalize: (a, g) => ({
      api: a.REFERENCE,
      wellName: a.NAME,
      operator: null,
      status: null,
      wellType: null,
      ...geomFirst(a, g),
      depth: a.LENGTH > 0 ? a.LENGTH : null,
      depthUnit: "m",
      yearKnown: a.YEAR_KNOWN,
      gridRef: a.GRID_REF,
      scanUrl: a.SCAN_URL,
    }),
  },
  {
    key: "NL-NLOG",
    country: "NL",
    state: null,
    kind: "wfs",
    label: "Netherlands deep boreholes (oil, gas, geothermal, salt, storage; onshore and offshore)",
    probe: { operator: "Trias" },
    agency: "TNO / NLOG (Dutch Oil and Gas Portal)",
    url: "https://www.gdngeoservices.nl/geoserver/ows",
    typeName: "nlog:gdw_ng_wll_all_utm",
    geometryName: "GEOMETRY",
    sortBy: "BOREHOLE_CODE",
    pageMax: 2000,
    idKind: "id",
    idLabel: "borehole code (e.g. 'NLW-GT-01')",
    extent: [2.5, 50.7, 7.3, 55.9],
    caveat: "Includes ~150 geothermal wells: well_type 'geothermic' (types 'Geothermic energy exploration' and 'Development geothermic energy production'). Depths in metres along hole (MD) and true vertical (TVD).",
    searchFields: {
      api: "BOREHOLE_CODE",
      well_name: "BOREHOLE_NAME",
      operator: "CURRENT_OWNER",
      field: "FIELD_NAME",
      status: "STATUS",
      well_type: "BOREHOLE_TYPE_DESCRIPTION",
    },
    normalize: (a, g) => ({
      api: a.BOREHOLE_CODE,
      uwi: a.UWI,
      wellName: a.BOREHOLE_NAME,
      operator: a.CURRENT_OWNER,
      originalOperator: a.ORIGINAL_OPERATOR,
      status: a.STATUS,
      wellType: a.BOREHOLE_TYPE_DESCRIPTION,
      result: a.BOREHOLE_RESULT_DESCRIPTION,
      field: a.FIELD_NAME,
      facility: a.MINING_FACILITY_NAME,
      offshore: a.ON_OFFSHORE_CODE === "OFF" ? true : a.ON_OFFSHORE_CODE === "ON" ? false : null,
      latitude: g?.y ?? null,
      longitude: g?.x ?? null,
      spudDate: isoDate(a.START_DATE_DRILLING),
      endDrillDate: isoDate(a.END_DATE_DRILLING),
      depthMD: nz(a.END_DEPTH_MAH),
      depthTVD: nz(a.END_DEPTH_MTVD),
      formationAtTd: a.LITHOSTRAT_CODE_AT_END_DEPTH,
      detailUrl: a.URL,
    }),
  },
  {
    key: "IS-OS",
    country: "IS",
    state: null,
    kind: "wfs",
    label: "Iceland borehole registry (geothermal production, reinjection, gradient wells...)",
    probe: { field: "Hellishei" },
    agency: "Orkustofnun (National Energy Authority) via the national geoportal",
    url: "https://gis.lmi.is/geoserver/ows",
    typeName: "orkustofnun:gisborhola",
    geometryName: "geom",
    sortBy: "audkenni",
    pageMax: 2000,
    idKind: "id",
    idLabel: "Orkustofnun borehole number (audkenni)",
    extent: [-24.6, 63.2, -13.3, 66.6],
    caveat:
      "Field names are Icelandic: field = geothermal area (svaedisnafn), operator = client (verkkaupi), well_type = purpose (e.g. 'Gufu' steam, 'Heitavatn' hot water, 'Niðurdæling' reinjection). Search Icelandic text without accents where possible ('Hellishei'). Borehole names like 'HE-10' are not unique.",
    searchFields: {
      api: "audkenni",
      well_name: "borholunofn",
      operator: "verkkaupi",
      county: "heitinew",
      field: "svaedisnafn",
      well_type: "tilgangurborunar",
    },
    normalize: (a, g) => ({
      api: a.audkenni != null ? String(a.audkenni) : null,
      wellName: a.borholunofn,
      operator: a.verkkaupi,
      owner: a.eigandiholu && a.eigandiholu !== "Ekki skráð" ? a.eigandiholu : null,
      status: null,
      wellType: a.tilgangurborunar,
      purpose: ICELAND_PURPOSE[a.idtilgangur] ?? null,
      field: a.svaedisnafn,
      county: a.heitinew,
      latitude: g?.y ?? null,
      longitude: g?.x ?? null,
      spudDate: dmyToIso(a.borun),
      depth: looseNum(a.dypi),
      depthUnit: "m",
      drillingContractor: a.eigandibors || null,
      detailUrl: a.tengill || null,
    }),
  },
  {
    key: "DE-LBEG",
    country: "DE",
    state: null,
    kind: "wfs",
    dialect: "fes", // cardo.map server
    label: "Germany deep wells (hydrocarbon, storage, salt, geothermal) - North German Basin, North Sea, Upper Rhine",
    probe: { well_name: "Bockstedt" },
    agency: "LBEG - Landesamt für Bergbau, Energie und Geologie (NIBIS)",
    url: "https://nibis.lbeg.de/net3/public/ogc.ashx?NodeId=287",
    typeName: "cls:L377",
    geometryName: "SHAPE",
    outputFormat: "application/geo+json",
    noPaging: true, // the server ignores startIndex
    pageMax: 2000,
    idKind: "id",
    idLabel: "LBEG well identifier",
    extent: [3.9, 47.5, 15.1, 55.9],
    caveat:
      "Labels are German: status (L_STATUS) Verfüllt = plugged, Offen = open; well_type (B_ART) e.g. Erdölbohrung (oil), Gasbohrung (gas), Geothermikbohrung (geothermal); result e.g. Ölfündig (oil found), Nicht fündig (dry). Depths in metres. Bavaria is not covered.",
    searchFields: {
      api: "IDENTIFIER",
      well_name: "LOCHNAME",
      operator: "FIRMA",
      status: "L_STATUS",
      well_type: "B_ART",
    },
    normalize: (a, g) => ({
      api: a.IDENTIFIER,
      wellName: a.LOCHNAME,
      operator: a.FIRMA,
      originalOperator: a.OPERATOR,
      status: a.L_STATUS,
      wellType: a.B_ART,
      wellClass: a.B_KLASSE2,
      result: a.G_ERGEBNIS || a.T_ERGEBNIS || null,
      latitude: g?.y ?? null,
      longitude: g?.x ?? null,
      spudDate: dmyToIso(a.BOHRBEGINN),
      endDrillDate: dmyToIso(a.BOHRENDE),
      depthMD: nz(a.ENDTIEFE),
      formationAtTd: a.E_HORIZO_L,
      logs: a.LOGDATEN,
    }),
  },
  {
    key: "PL-PGI",
    country: "PL",
    state: null,
    label: "Poland borehole database (all purposes, incl. geothermal)",
    probe: { well_type: "Earth's heat" },
    agency: "Polish Geological Institute (PGI-PIB, CBDG)",
    url: "https://cbdgmapa.pgi.gov.pl/arcgis/rest/services/cbdg_otwory_web/FeatureServer/0",
    pageMax: 2000,
    idKind: "id",
    idLabel: "CBDG borehole id",
    apiNumeric: true,
    extent: [14.0, 49.0, 24.2, 55.0],
    caveat: "All boreholes (deposits, research, hydrogeology, engineering...). well_type 'Earth's heat' = geothermal. No operator or status; year only. Polish diacritics in search text may not match.",
    searchFields: {
      api: "ID_CBDG",
      well_name: "NAZWA",
      county: "WOJEWODZTWO",
      well_type: "CEL_W_EN",
    },
    normalize: (a, g) => ({
      api: a.ID_CBDG != null ? String(a.ID_CBDG) : null,
      wellName: a.NAZWA,
      operator: null,
      status: null,
      wellType: a.CEL_W_EN,
      county: a.WOJEWODZTWO,
      district: a.POWIAT,
      ...geomFirst(a, g),
      year: a.ROK,
      depth: nz(a.GLEBOKOSC),
      depthUnit: "m",
      formationAtTd: a.STRAT_EN,
    }),
  },
  ...[
    // offshore spud dates are long-form ('Wednesday, April 25, 2001'); onshore are DD/MM/YYYY
    ["IE-OFF", 1, "Ireland offshore petroleum wells", { operator: "Shell" }, [-18.0, 48.0, -5.0, 57.5], namedDateToIso],
    ["IE-ON", 2, "Ireland onshore petroleum wells", { operator: "Aran" }, [-10.7, 51.3, -5.9, 55.5], dmyToIso],
  ].map(([key, layer, label, probe, extent, spud]) => ({
    key,
    country: "IE",
    state: null,
    label,
    probe,
    agency: "Petroleum Affairs Division (Department of the Environment, Climate and Communications)",
    url: `https://services2.arcgis.com/9g6TNz2FCkMRX6Tw/arcgis/rest/services/GSRO_Offshore_Data/FeatureServer/${layer}`,
    pageMax: 2000,
    idKind: "id",
    idLabel: "well number (e.g. '48/25-4')",
    extent,
    caveat: "Small dataset on a departmental ArcGIS Online account. Depths in the unit given (usually ft).",
    searchFields: {
      api: "WELL_NUM",
      well_name: "WELL_NUM",
      operator: "OPERATOR",
      status: "STATUS",
      ...(layer === 1 ? { well_type: "WELL_CLASS" } : {}),
    },
    normalize: (a, g) => ({
      api: a.WELL_NUM,
      wellName: a.WELL_NUM,
      operator: a.OPERATOR,
      status: a.STATUS,
      result: a.RESULT,
      wellType: a.WELL_CLASS ?? null,
      ...geomFirst(a, g),
      spudDate: spud(a.WELL_SPUD), // START_DATE is only the year's first day
      depth: nz(a.WELL_DEPTH),
      depthUnit: a.UNIT ?? null,
      waterDepth: nz(a.WATER_DEP),
    }),
  })),
  {
    key: "DK-GEUS",
    country: "DK",
    state: null,
    kind: "wfs",
    dialect: "fes", // MapServer
    label: "Denmark released exploration wells (onshore and offshore)",
    probe: { operator: "Texaco" },
    agency: "GEUS - Geological Survey of Denmark and Greenland (Samba)",
    url: "https://data.geus.dk/geusmap/ows/4326.jsp",
    typeName: "ms:samba_petroleum_wellbores_test",
    geometryName: "msGeometry",
    pageMax: 1000,
    idKind: "id",
    idLabel: "well number (e.g. '5410/05-01')",
    extent: [3.0, 54.4, 15.3, 58.0],
    caveat: "Released exploration wells only (no development wells). Danish letters matter: 'MÆRSK' does not match 'maersk'.",
    searchFields: {
      api: "well_numb",
      well_name: "well_name",
      operator: "operator",
      well_type: "classification",
    },
    normalize: (a, g) => ({
      api: a.well_numb,
      wellName: a.well_name,
      operator: a.operator,
      status: a.content_status || null,
      wellType: a.classification,
      content: a.content,
      licence: a.licence,
      offshore: a.location === "OFFSHORE" ? true : a.location === "ONSHORE" ? false : null,
      ...geomFirst(a, g, "n_degrees", "e_degrees"),
      spudDate: isoDate(a.spud_da),
      completionDate: isoDate(a.comp_da),
      detailUrl: a.well_info,
    }),
  },
  {
    key: "EU-GSEU",
    country: "EU",
    state: null,
    kind: "wfs",
    dialect: "fes", // MapServer
    label: "Pan-European deep boreholes with bottom-hole temperatures (25 national surveys)",
    probe: { operator: "Orkuveita" },
    agency: "Geological Service for Europe (GSEU) via EGDI",
    url: "https://maps.europe-geology.eu/wfs/",
    typeName: "ms:gseu_level0_boreholes",
    geometryName: "msGeometry",
    pageMax: 1000,
    idKind: "id",
    idLabel: "GSEU borehole id (e.g. 'IS_well_026')",
    extent: [-32.0, 34.0, 45.0, 72.0],
    caveat:
      "Harmonised compilation (~42k boreholes) from 25 surveys - the only keyless source found for Hungary, Austria, Croatia, Romania, Greece, Spain and Portugal incl. the Azores. county filters by country name. Labels are inconsistent across countries (and some characters are mangled); drill year only. bhtC = bottom-hole temperature.",
    searchFields: {
      api: "id",
      well_name: "well_name",
      operator: "company",
      county: "country",
      status: "status",
      well_type: "purpose",
    },
    normalize: (a, g) => ({
      api: a.id,
      wellName: a.well_name,
      operator: a.company,
      status: a.status,
      wellType: a.purpose,
      county: a.country,
      ...geomFirst(a, g),
      drillYear: a.drill_year,
      depthTVD: nz(a.tvd),
      bhtC: nz(a.bht),
      gradient: nz(a.gradient),
      meanSurfaceTempC: nz(a.mean_sur_t),
      tdsMgL: nz(a.geoch_tds),
      contributingSurvey: a.source,
    }),
  },
];
