// New Zealand and Australia. Every endpoint and field name below was verified against
// a live response on 2026-10-06.

import { msToIso, isoDate, coord, num, geomFirst } from "./normalize.js";

const nz = (v) => num(v, { zeroIsNull: true });
const AUSTRALIA = [112.0, -45.0, 155.0, -9.0];

// South Australia's petroleum and geothermal layers share one schema.
function sarig({ key, typeName, label, probe, caveat }) {
  return {
    key,
    country: "AU",
    state: "SA",
    kind: "wfs",
    label,
    probe,
    agency: "Government of South Australia, Department for Energy and Mining (SARIG)",
    url: "https://services.sarig.sa.gov.au/vector/drillholes/wfs",
    typeName,
    geometryName: "WKB_GEOMETRY",
    sortBy: "DRILLHOLE_NO",
    pageMax: 2000,
    idKind: "id",
    idLabel: "SARIG drillhole number",
    extent: [129.0, -38.1, 141.0, -26.0],
    license: "CC BY 4.0",
    caveat,
    searchFields: {
      api: "DRILLHOLE_NO",
      well_name: "WELL_NAME",
      operator: "OPERATOR",
      county: "BASIN",
      field: "NAME",
      status: "STATUS_RIG_RELEASE",
      well_type: "WELL_TYPE",
    },
    normalize: (a, g) => ({
      api: a.DRILLHOLE_NO != null ? String(a.DRILLHOLE_NO) : null,
      wellName: a.WELL_NAME,
      operator: a.OPERATOR,
      status: a.STATUS_RIG_RELEASE,
      wellType: a.WELL_TYPE,
      wellClass: a.CLASS,
      field: a.NAME,
      county: a.BASIN,
      ...geomFirst(a, g, "LATITUDE__DEC", "LONGITUDE__DEC"),
      spudDate: isoDate(a.SPUDDED),
      rigReleaseDate: isoDate(a.RIG_RELEASE),
      depthMD: nz(a.TD__M),
      depthUnit: "m",
      tenement: [a.TENEMENT, a.TENNUM].filter(Boolean).join(" ") || null,
      access: a.SECURITY,
    }),
  };
}

// Queensland's petroleum and coal-seam-gas layers share one schema.
function queensland({ key, layer, label, probe }) {
  return {
    key,
    country: "AU",
    state: "QLD",
    label,
    probe,
    agency: "Geological Survey of Queensland",
    url: `https://spatial-gis.information.qld.gov.au/arcgis/rest/services/GeoscientificInformation/Boreholes/MapServer/${layer}`,
    pageMax: 2000,
    idKind: "id",
    idLabel: "GSQ borehole number",
    apiNumeric: true,
    extent: [137.9, -29.2, 153.6, -9.0],
    license: "CC BY 4.0",
    caveat: "Updated nightly. No spud date (rigReleaseDate is the end of drilling). Depths in metres.",
    searchFields: {
      api: "bore_no",
      well_name: "bore_name",
      operator: "operator_name",
      status: "status",
      well_type: "bore_subtype",
    },
    normalize: (a, g) => ({
      api: a.bore_no != null ? String(a.bore_no) : null,
      wellName: a.bore_name,
      operator: a.operator_name,
      status: a.status,
      wellType: a.bore_subtype || a.bore_type,
      result: a.result,
      ...geomFirst(a, g, "latitude", "longitude"),
      rigReleaseDate: msToIso(a.rig_release_date),
      depthMD: nz(a.total_depth_driller),
      depthUnit: "m",
      tenure: [a.tenure_type, a.tenure_no].filter(Boolean).join(" ") || null,
      reportUrl: a.company_report_link,
      dataUrl: a.qdex_data_link,
    }),
  };
}

export const OCEANIA_SOURCES = [
  // ------------------------------------------------------------ New Zealand
  {
    key: "NZ-PET",
    country: "NZ",
    state: null,
    label: "New Zealand petroleum wells (nationwide, incl. offshore)",
    probe: { operator: "Todd" },
    agency: "NZ Petroleum & Minerals (NZP&M)",
    url: "https://gis.nzpam.govt.nz/server/rest/services/Public/GeodataCatalogue_Layers/FeatureServer/4",
    pageMax: 2000,
    idKind: "id",
    idLabel: "UWI",
    extent: [165.0, -52.0, 179.99, -33.0],
    noReproject: true, // server 500s on outSR; layer has Latitude/Longitude fields
    emptyResultBug: true, // server also 500s on zero-match queries instead of returning []
    caveat: "Petroleum wells only. Geothermal wells: NZ-WAIKATO and NZ-BOP (regional councils).",
    searchFields: {
      api: "UWI",
      well_name: "Title",
      operator: "Operator",
      field: "Prospect_Field",
      status: "Status_Public",
      well_type: "Type",
    },
    normalize: (a, g) => ({
      api: a.UWI,
      wellName: a.Title,
      alias: a.Alias || null,
      operator: a.Operator,
      status: a.Status_Public,
      wellType: a.Type,
      purpose: a.Purpose,
      field: a.Prospect_Field,
      county: null,
      latitude: coord(a, "Latitude", g, "y"),
      longitude: coord(a, "Longitude", g, "x"),
      spudDate: msToIso(a.Start_Date),
      endDate: msToIso(a.End_Date),
      depthMD: a.Total_Depth_Public,
      permit: a.Permit,
      openFile: a.Open_File,
    }),
  },
  {
    key: "NZ-WAIKATO",
    country: "NZ",
    state: "WKO",
    label: "Waikato geothermal wells (Taupō Volcanic Zone, incl. deep production wells)",
    probe: { status: "Existing" },
    agency: "Waikato Regional Council (National Wells Database)",
    url: "https://services.arcgis.com/2bzQ0Ix3iO7MItUa/arcgis/rest/services/WDP_WELLS_UNIQUE/FeatureServer/0",
    pageMax: 2000,
    idKind: "id",
    idLabel: "Waikato well identifier (e.g. '72_3342')",
    baseWhere: "GEOTHERMAL = 'Yes'",
    // Address/location-description fields hold home addresses of domestic bores: never requested.
    outFields:
      "WELL_ID,IDENTIFIER,WELL_NAME,WELL_TYPE,WELL_STATUS,DRILLING_DATE,COMPANY_NAME,ACTUAL_LATITUDE,ACTUAL_LONGITUDE,LOCATION_ACCURACY,ACTUAL_DEPTH_DRILLED,MAX_TEMPERATURE,AQUIFER_TYPE,GEOTHERMAL,HAS_GEOTHERMAL_INFLUENCE",
    extent: [174.4, -39.4, 176.9, -36.5],
    license: "CC BY 4.0 (Waikato Regional Council)",
    caveat:
      "Geothermal wells only (from shallow heating bores to deep power-station wells). Names are generic ('Bore 72 - Station 3342'), not operator well names; driller is the drilling contractor, not the operator. Depths in metres.",
    searchFields: {
      api: "IDENTIFIER",
      well_name: "WELL_NAME",
      status: "WELL_STATUS",
      well_type: "WELL_TYPE",
    },
    normalize: (a, g) => ({
      api: a.IDENTIFIER,
      wellId: a.WELL_ID,
      wellName: a.WELL_NAME,
      operator: null,
      driller: a.COMPANY_NAME,
      status: a.WELL_STATUS,
      wellType: a.WELL_TYPE,
      ...geomFirst(a, g, "ACTUAL_LATITUDE", "ACTUAL_LONGITUDE"),
      spudDate: msToIso(a.DRILLING_DATE),
      depthMD: nz(a.ACTUAL_DEPTH_DRILLED),
      maxTemperature: num(a.MAX_TEMPERATURE),
      aquifer: a.AQUIFER_TYPE,
    }),
  },
  {
    key: "NZ-BOP",
    country: "NZ",
    state: "BOP",
    label: "Bay of Plenty geothermal bores (Rotorua, Tauranga...)",
    probe: { field: "Rotorua" },
    agency: "Bay of Plenty Regional Council",
    url: "https://services1.arcgis.com/TWsoAGve3wb3oFHK/arcgis/rest/services/WellBoreLocations/FeatureServer/0",
    pageMax: 2000,
    idKind: "id",
    idLabel: "BOPRC bore reference (e.g. 'BN-1000115')",
    baseWhere: "BoreType = 'Geothermal'",
    outFields:
      "BOPRC_Ref,Status,BoreStatus,BoreUse,BoreType,GeothermalField,BoreDepth_m,CasingDepth_m,DrillingDate,BoreTemp_degC,ConsentNumber,Purpose,DataSource",
    extent: [175.8, -39.5, 178.6, -37.3],
    license: "CC BY-ND (Bay of Plenty Regional Council): query live; don't redistribute modified extracts",
    caveat: "Consented geothermal bores; the Kawerau power-station wells are largely absent. Depths in metres, temperatures in deg C.",
    searchFields: {
      api: "BOPRC_Ref",
      field: "GeothermalField",
      status: "BoreStatus",
      well_type: "BoreUse",
    },
    normalize: (a, g) => ({
      api: a.BOPRC_Ref,
      wellName: a.BOPRC_Ref,
      operator: null,
      status: a.BoreStatus || a.Status,
      wellType: a.BoreUse,
      purpose: a.Purpose,
      field: a.GeothermalField,
      ...geomFirst(a, g),
      spudDate: msToIso(a.DrillingDate),
      depthMD: nz(a.BoreDepth_m),
      temperatureC: num(a.BoreTemp_degC),
      consent: a.ConsentNumber,
    }),
  },

  // ---------------------------------------------------------------- Australia
  {
    key: "AU-GA",
    country: "AU",
    state: null,
    kind: "wfs",
    label: "Australia national borehole database (petroleum, coal-seam gas, geothermal, stratigraphic)",
    probe: { well_type: "geothermal" },
    agency: "Geoscience Australia",
    url: "https://services.ga.gov.au/gis/boreholes/wfs",
    typeName: "bh:Boreholes",
    geometryName: "SHAPE",
    sortBy: "ENO",
    pageMax: 2000,
    idKind: "id",
    idLabel: "GA borehole number (ENO)",
    extent: AUSTRALIA,
    license: "CC BY 4.0",
    caveat: "National compilation (~52k boreholes, onshore and offshore). State sources (AU-SA-*, AU-QLD-*, AU-WA) are fresher and richer for their states. Lengths in metres.",
    searchFields: {
      api: "ENO",
      well_name: "NAME",
      operator: "OPERATOR",
      status: "STATUS",
      well_type: "PURPOSE",
    },
    normalize: (a, g) => ({
      api: a.ENO != null ? String(a.ENO) : null,
      wellName: a.NAME,
      operator: a.OPERATOR,
      status: a.STATUS,
      wellType: a.PURPOSE,
      ...geomFirst(a, g, "COLLAR_LAT_GDA94", "COLLAR_LONG_GDA94"),
      spudDate: isoDate(a.DRILLSTARTDATE),
      endDrillDate: isoDate(a.DRILLENDDATE),
      depthMD: nz(a.BOREHOLELENGTH_M),
      depthUnit: "m",
      startPoint: a.STARTPOINT,
      custodian: a.DATA_CUSTODIAN,
      uri: a.IDENTIFIER,
    }),
  },
  sarig({
    key: "AU-SA-PET",
    typeName: "drillholes:petroleum_wells",
    label: "South Australia petroleum wells (Cooper/Eromanga...)",
    probe: { operator: "Santos" },
    caveat: "Depths in metres. field is the field/prospect name.",
  }),
  sarig({
    key: "AU-SA-GEO",
    typeName: "drillholes:geothermal_wells",
    label: "South Australia geothermal wells (incl. Habanero)",
    probe: { well_name: "Habanero" },
    caveat: "Hot-rock and hot-sedimentary-aquifer geothermal wells. Depths in metres.",
  }),
  queensland({
    key: "AU-QLD-PET",
    layer: 8,
    label: "Queensland petroleum wells",
    probe: { operator: "Santos" },
  }),
  queensland({
    key: "AU-QLD-CSG",
    layer: 1,
    label: "Queensland coal-seam-gas wells",
    probe: { well_name: "Broadmeadow" },
  }),
  {
    key: "AU-WA",
    country: "AU",
    state: "WA",
    label: "Western Australia onshore petroleum wells",
    probe: { county: "Perth" },
    agency: "WA Department of Energy, Mines, Industry Regulation and Safety (DMIRS-025)",
    url: "https://public-services.slip.wa.gov.au/public/rest/services/SLIP_Public_Services/Industry_and_Mining/MapServer/13",
    pageMax: 2000,
    idKind: "id",
    idLabel: "UWI",
    extent: [112.9, -35.2, 129.1, -13.6],
    license: "CC BY 4.0",
    caveat: "Onshore wells, updated daily. county filters by basin. No depth field.",
    searchFields: {
      api: "uwi",
      well_name: "well_name",
      operator: "operator",
      county: "basin",
      field: "field",
      status: "status",
      well_type: "class",
    },
    normalize: (a, g) => ({
      api: a.uwi,
      wellName: a.well_name,
      operator: a.operator,
      status: a.status,
      wellType: a.class,
      field: a.field,
      county: a.basin,
      ...geomFirst(a, g, "lat", "long"),
      spudDate: msToIso(a.spud_date),
      rigReleaseDate: msToIso(a.rig_release_date),
      lease: a.lease_no,
    }),
  },
];
