// US state regulator and survey sources (ArcGIS REST layers unless `kind` says otherwise).
// Every endpoint and field name below was verified against a live response; the date
// in each comment is the last time it was. Adding a state = adding an entry here.
// Federal offshore (BOEM) sources live in boem.js.

import { msToIso, usDateToIso, isoDate, ymdToIso, coord, num, geomFirst, joinName, centroid } from "./normalize.js";
import { USER_AGENT } from "../meta.js";

const nz = (v) => num(v, { zeroIsNull: true });

const STATE_SOURCES = [
  // ------------------------------------------------------------------ West
  {
    key: "CA-OG",
    state: "CA",
    label: "California oil & gas wells",
    probe: { operator: "California Resources" },
    agency: "CalGEM (WellSTAR)",
    url: "https://gis.conservation.ca.gov/server/rest/services/WellSTAR/Wells/MapServer/0",
    pageMax: 5000,
    searchFields: {
      api: "API",
      well_name: "LeaseName",
      operator: "OperatorName",
      county: "CountyName",
      field: "FieldName",
      status: "WellStatus",
      well_type: "WellTypeLabel",
    },
    normalize: (a, g) => ({
      api: a.API,
      wellName: joinName(a.LeaseName, a.WellNumber),
      operator: a.OperatorName,
      status: a.WellStatus,
      wellType: a.WellTypeLabel ?? a.WellType,
      field: a.FieldName,
      county: a.CountyName,
      latitude: coord(a, "Latitude", g, "y"),
      longitude: coord(a, "Longitude", g, "x"),
      spudDate: usDateToIso(a.SpudDate),
      district: a.District,
      confidential: a.isConfidential,
    }),
  },
  {
    key: "CA-GEO",
    state: "CA",
    label: "California geothermal wells",
    probe: { operator: "Calpine" },
    agency: "CalGEM (WellSTAR)",
    url: "https://gis.conservation.ca.gov/server/rest/services/WellSTAR/Wells/MapServer/1",
    pageMax: 5000,
    searchFields: {
      api: "APINumber",
      well_name: "LeaseName",
      operator: "OperatorName",
      county: "CountyName",
      field: "FieldName",
      status: "WellStatusDescription",
      well_type: "WellType",
    },
    normalize: (a, g) => ({
      api: a.APINumber,
      wellName: joinName(a.LeaseName, a.WellNumber) || a.WellDesignation,
      operator: a.OperatorName,
      status: a.WellStatusDescription ?? a.WellStatus,
      wellType: a.WellType,
      field: a.FieldName,
      county: a.CountyName,
      latitude: coord(a, "Lat83", g, "y"),
      longitude: coord(a, "Long83", g, "x"),
      // live layer types these as Integer and they are null on every row checked 2026-09-15;
      // usDateToIso handles either a US string or an epoch number if CalGEM starts filling them
      spudDate: usDateToIso(a.SpudDate),
      completionDate: usDateToIso(a.CompDate),
      abandonDate: usDateToIso(a.ABDdate),
      directional: a.Directional,
    }),
  },
  {
    key: "UT",
    state: "UT",
    label: "Utah oil & gas wells",
    probe: { operator: "Ovintiv" },
    agency: "Utah Division of Oil, Gas & Mining (DOGM)",
    // DOGM's own published layer (owner OGMGIS_utahDNR); verified 2026-10-06.
    url: "https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/viewAGRC_WellData_Surf/FeatureServer/0",
    pageMax: 2000,
    caveat:
      "Oil & gas only - DOGM regulates no geothermal wells. Utah geothermal wells (Fervo Cape Station, Utah FORGE) are in UT-GEO and UT-WLOG (Division of Water Rights).",
    searchFields: {
      api: "API",
      well_name: "WellName",
      operator: "Operator",
      county: "County",
      field: "FieldName",
      status: "WellStatus",
      well_type: "WellType",
    },
    normalize: (a, g) => ({
      api: a.API,
      wellName: a.WellName,
      operator: a.Operator,
      status: a.WellStatus,
      wellType: a.WellType,
      field: a.FieldName,
      county: a.County,
      ...geomFirst(a, g, "Latitude", "Longitude"),
      spudDate: null,
      completionDate: msToIso(a.OrigComplDate),
      abandonDate: msToIso(a.AbandonDate),
      cumOilBbl: a.TotCum_Oil,
      cumGasMcf: a.TotCum_Gas,
      cumWaterBbl: a.TotCum_Water,
      leaseType: a.LeaseType,
      unitName: a.UnitName,
      confidential: a.Confidential,
    }),
  },
  {
    key: "UT-GEO",
    state: "UT",
    label: "Utah deep geothermal wells (incl. Fervo Cape Station, Utah FORGE)",
    probe: { operator: "Fervo" },
    agency: "Utah Division of Water Rights (DWRi)",
    // Curated DWRi layer under the Geothermal Resource Conservation Act; verified 2026-10-06.
    url: "https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/Geothermal_Wells/FeatureServer/1",
    pageMax: 2000,
    idKind: "id",
    idLabel: "DWRi well id (WIN)",
    baseWhere: "Well_Name IS NOT NULL", // the layer carries a few all-null placeholder rows
    caveat:
      "A short curated list DWRi updates periodically (not live). Depths are in feet. Every drilled well, including newer Cape Station wells not yet listed here, is in UT-WLOG.",
    searchFields: {
      api: "WIN",
      well_name: "Well_Name",
      operator: "Operator",
      field: "KGRA",
      status: "Status",
      well_type: "Type1",
    },
    normalize: (a, g) => ({
      api: a.WIN && a.WIN !== "NA" ? a.WIN : null,
      wellName: a.Well_Name,
      operator: a.Operator,
      status: a.Status,
      wellType: a.Type1,
      trajectory: a.Type,
      field: a.KGRA,
      county: null,
      ...geomFirst(a, g, "Lat", "Long"),
      completionDate: msToIso(a.Completion_date),
      depthMD: nz(a.MD_ft_),
      depthTVD: nz(a.TVD_ft_),
      approval: a.Approval,
      landOwner: a.Land_Owner,
      wellLogUrl: /^\d+$/.test(String(a.WIN)) ? `https://waterrights.utah.gov/wellinfo/welldrilling/wlbrowse.asp?WIN=${a.WIN}` : null,
    }),
  },
  {
    key: "UT-WLOG",
    state: "UT",
    label: "Utah drilled-well logs (every well drilled under a water-rights approval, incl. geothermal)",
    probe: { operator: "Escalante Desert" },
    agency: "Utah Division of Water Rights (DWRi)",
    url: "https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/Utah_Well_Logs/FeatureServer/0",
    pageMax: 2000,
    idKind: "id",
    idLabel: "DWRi well id (WIN)",
    apiNumeric: true,
    caveat:
      "Mostly water wells, with no geothermal flag: find geothermal wells by owner or with wells_near. Fervo's Cape Station wells are owned by 'ESCALANTE DESERT RESOURCES LLC'; Utah FORGE's by 'ENERGY GEOSCIENCE INSTITUTE'. No name, status, date or depth fields - each record's wellLogUrl opens the DWRi page with driller, dates, depth and well name.",
    searchFields: {
      api: "WIN",
      operator: "Owner",
    },
    normalize: (a, g) => ({
      api: a.WIN != null ? String(a.WIN) : null,
      wellName: null,
      operator: a.Owner,
      status: null,
      wellType: null,
      ...geomFirst(a, g, "Latitude", "Longitude"),
      approval: a.WRCHEX,
      location: a.Location,
      logType: a.Log_Type,
      wellLogUrl: a.LINK,
    }),
  },
  {
    key: "UT-THERMAL",
    state: "UT",
    label: "Utah thermal wells and springs (temperature + water chemistry)",
    probe: { field: "Roosevelt" },
    agency: "Utah Geological Survey (UGS)",
    url: "https://webmaps.geology.utah.gov/arcgis/rest/services/Energy_Mineral/Geotherm_Well_Spring/MapServer/0",
    pageMax: 1000,
    idKind: "id",
    idLabel: "UGS map number",
    caveat: "Geothermal resource inventory: thermal wells and hot springs with measured temperature (deg C), depth and water chemistry. Not a permit registry - no operator or status.",
    searchFields: {
      api: "MAPNO",
      well_name: "SOURCE",
      county: "COUNTY",
      field: "REGION_LOC",
    },
    normalize: (a, g) => ({
      api: a.MAPNO,
      wellName: a.SOURCE,
      operator: null,
      status: a.STATUS,
      wellType: { W: "Well", S: "Spring" }[a.TYPE] ?? a.TYPE,
      field: a.REGION_LOC,
      county: a.COUNTY,
      ...geomFirst(a, g, "LAT", null),
      temperatureC: num(a.TEMP),
      depth: num(a.DEPTH),
      sampleDate: msToIso(a.DATE),
      flow: num(a.FLOW),
      pH: num(a.PH),
      tdsMgL: num(a.TDSM),
      reference: a.REFERENCE,
    }),
  },
  {
    key: "NM",
    state: "NM",
    label: "New Mexico oil & gas wells",
    probe: { operator: "Devon" },
    agency: "NM OCD (EMNRD)",
    url: "https://gis.emnrd.nm.gov/arcgis/rest/services/OCDView/Wells_Public/FeatureServer/0",
    pageMax: 6000,
    searchFields: {
      api: "id",
      well_name: "name",
      operator: "ogrid_name",
      county: "county",
      status: "status",
      well_type: "type",
    },
    normalize: (a, g) => ({
      api: a.id,
      wellName: a.name,
      operator: a.ogrid_name,
      status: a.status,
      wellType: a.type,
      field: a.pool_id_list ?? null,
      county: a.county,
      latitude: coord(a, "latitude", g, "y"),
      longitude: coord(a, "longitude", g, "x"),
      spudDate: msToIso(a.spud_date),
      depthMD: a.measured_vertical_depth,
      depthTVD: a.true_vertical_depth,
      lastProductionDate: msToIso(a.last_production_date),
      plugDate: msToIso(a.plug_date),
      directional: a.directional_status,
    }),
  },
  {
    key: "CO",
    state: "CO",
    label: "Colorado wells (API spots)",
    probe: { operator: "Chevron" },
    agency: "Colorado ECMC (via DNR GIS)",
    // Field names re-verified against …/MapServer/0?f=json on 2026-09-15 (post ECMC cutover).
    url: "https://gisdnr.state.co.us/arcgis/rest/services/ECMC_Public/ECMC_Wells/MapServer/0",
    pageMax: 2000,
    searchFields: {
      api: "API",
      well_name: "WellName",
      operator: "Operator",
      county: "COUNTY",
      field: "field_name",
      status: "wellstat",
      well_type: "well_class",
    },
    normalize: (a, g) => ({
      api: a.API,
      wellName: a.WellName ?? a.well_name,
      operator: a.Operator,
      status: a.wellstat,
      wellType: a.well_class || null,
      field: a.field_name || a.BASIN || null,
      county: a.COUNTY ?? null,
      latitude: coord(a, "lat", g, "y"),
      longitude: coord(a, "long", g, "x"),
      spudDate: msToIso(a.spud_date),
      statusDate: msToIso(a.status_date),
      depthMD: a.max_m_depth || null,
      depthTVD: a.max_tv_depth || null,
      basin: a.BASIN ?? null,
    }),
  },
  {
    key: "WY",
    state: "WY",
    label: "Wyoming oil & gas wells (WOGCC database snapshot)",
    probe: { operator: "EOG" },
    agency: "Wyoming State Geological Survey (copy of the WOGCC well database)",
    url: "https://portal.wsgs.wyo.gov/ags/rest/services/OilGas/SDE_All_WOGCCWells/FeatureServer/5",
    pageMax: 2000,
    caveat:
      "Rich (operator, field, dates, depth) but a snapshot: the newest spud is January 2025, so recent wells and current status are missing - WY-LIVE has WOGCC's live list (name, status, type only). Status and class are WOGCC codes (status e.g. PA permanently abandoned, PR producing, SI shut-in, TA temporarily abandoned, SP spudded, AI active injector, DH dry hole).",
    searchFields: {
      api: "CAPINO",
      well_name: "UNIT_LEASE",
      operator: "COMPANY",
      county: "COUNTYTXT",
      field: "FIELD_NAME",
      status: "STATUS",
      well_type: "WELL_CLASS",
    },
    normalize: (a, g) => ({
      api: a.CAPINO,
      wellName: joinName(a.UNIT_LEASE, a.WN),
      operator: a.COMPANY,
      status: a.STATUS,
      wellType: a.WELL_CLASS,
      field: a.FIELD_NAME,
      county: a.COUNTYTXT,
      ...geomFirst(a, g, "LAT", "LON"),
      spudDate: ymdToIso(a.FIRSTSPUD),
      completionDate: ymdToIso(a.FIRSTCOMP),
      statusDate: ymdToIso(a.STATUSDATE),
      depthMD: nz(a.TD),
      basin: a.BASIN,
      bottomFormation: a.BOTFORM,
      horizontalOrDirectional: a.HORIZ_DIR,
      bottomHoleLatitude: nz(a.BLAT),
      bottomHoleLongitude: nz(a.BLON),
    }),
  },
  {
    key: "WY-LIVE",
    state: "WY",
    kind: "wfs",
    label: "Wyoming wells - live WOGCC list (name, status, type)",
    probe: { well_name: "Cork" },
    agency: "Wyoming Oil and Gas Conservation Commission (WOGCC) Data Explorer",
    url: "https://dataexplorer.wogcc.wyo.gov/geoserver/wfs",
    typeName: "WY_SHPS:WELL",
    geometryName: "the_geom",
    sortBy: "PKey",
    pageMax: 2000,
    caveat: "Current but thin: no operator, county, field, dates or depth (those are in WY, as of January 2025).",
    searchFields: {
      api: "WellId",
      well_name: "WellName",
      status: "WellStatus",
      well_type: "WellType",
    },
    normalize: (a, g) => ({
      api: a.WellId,
      wellName: a.WellName,
      operator: null,
      status: a.WellStatus,
      wellType: a.WellType,
      latitude: g?.y ?? null,
      longitude: g?.x ?? null,
      slant: a.Slant,
      confidential: a.Confid,
    }),
  },
  {
    key: "MT",
    state: "MT",
    label: "Montana oil & gas wells",
    probe: { operator: "Continental" },
    agency: "Montana Board of Oil & Gas Conservation (DNRC)",
    url: "https://services2.arcgis.com/DRQySz3VhPgOv7Bo/arcgis/rest/services/BOG_Wells/FeatureServer/1",
    pageMax: 2000,
    searchFields: {
      api: "APIWellNumber",
      well_name: "WellName",
      operator: "CompanyName",
      field: "ProductionField",
      status: "Status",
      well_type: "Type",
    },
    normalize: (a, g) => ({
      api: a.APIWellNumber,
      wellName: a.WellName,
      operator: a.CompanyName,
      status: a.Status,
      wellType: a.Type,
      field: a.ProductionField || a.Reg_Field,
      county: null,
      ...geomFirst(a, g),
      completionDate: usDateToIso(a.Completed),
      depthMD: nz(a.DTD),
    }),
  },
  {
    key: "ID-OG",
    state: "ID",
    label: "Idaho oil & gas wells",
    probe: { operator: "Snake River" },
    agency: "Idaho Geological Survey",
    url: "https://services.arcgis.com/WLhB60Nqwp4NnHz3/arcgis/rest/services/OilAndGas2023/FeatureServer/0",
    pageMax: 2000,
    caveat: "Idaho Geological Survey compilation (2023 edition, ~220 wells) with log/core availability flags.",
    searchFields: {
      api: "API",
      well_name: "WellName",
      operator: "Operator",
      county: "County",
      field: "FieldName",
      status: "WellStatus",
      well_type: "WellType",
    },
    normalize: (a, g) => ({
      api: a.API,
      wellName: a.WellName,
      operator: a.Operator,
      status: a.WellStatus,
      wellType: a.WellType,
      field: a.FieldName,
      county: a.County,
      ...geomFirst(a, g, "LatitudeWGS84", "LongitudeWGS84"),
      spudDate: usDateToIso(a.SpudDate),
      endDrillDate: usDateToIso(a.EndDrillDate),
      depthMD: nz(a.TotalDepth),
      hydrocarbonType: a.HydrocarbonType,
      geophysicalLogs: a.GeophysicalLogs,
    }),
  },
  {
    key: "ID-GEO",
    state: "ID",
    label: "Idaho geothermal wells (low-temperature use, with water temperatures)",
    probe: { well_type: "heating" },
    agency: "Idaho Department of Water Resources (IDWR)",
    url: "https://gis.idwr.idaho.gov/hosting/rest/services/Groundwater/GeothermalWells/FeatureServer/0",
    pageMax: 2000,
    idKind: "id",
    idLabel: "IDWR well id",
    apiNumeric: true,
    caveat: "Geothermal water wells (space heating, aquaculture, greenhouses...) with min/max water temperature; IDWR does not state the temperature unit (values suggest deg F). No operator or status.",
    searchFields: {
      api: "WellID",
      well_name: "StationName",
      well_type: "GeothermalUse",
    },
    normalize: (a, g) => ({
      api: a.WellID != null ? String(a.WellID) : null,
      siteId: a.AgencySiteID,
      wellName: a.StationName,
      operator: null,
      status: null,
      wellType: a.GeothermalUse,
      ...geomFirst(a, g, "LAT", null), // LONG is stored west-positive
      depth: nz(a.WellDepth),
      maxWaterTemp: num(a.MaxWaterTemp),
      maxWaterTempDate: msToIso(a.MaxWaterTempDate),
      minWaterTemp: num(a.MinWaterTemp),
      discharge: num(a.Discharge),
    }),
  },
  {
    key: "OR-GEO",
    state: "OR",
    label: "Oregon geothermal wells and temperature-gradient holes (incl. Newberry)",
    probe: { field: "Newberry" },
    agency: "Oregon DOGAMI (GTILO-2 compilation)",
    url: "https://gis.dogami.oregon.gov/arcgis/rest/services/Public/GTILO2/MapServer/0",
    pageMax: 1000,
    noPaging: true, // server 400s on resultOffset/resultRecordCount
    caveat:
      "DOGAMI's 2013 geothermal compilation (geothermal wells, gradient holes, some water wells): nothing drilled after about 2013. Max temperatures in the unit given by temperatureUnit. DOGAMI publishes no oil & gas well layer.",
    searchFields: {
      api: "APINo",
      well_name: "WellName_",
      operator: "Operator",
      county: "County",
      field: "Field",
      status: "Status",
      well_type: "WellType",
    },
    normalize: (a, g) => ({
      api: a.APINo,
      wellName: a.WellName_,
      operator: a.Operator,
      status: a.Status,
      wellType: a.WellType,
      field: a.Field,
      county: a.County,
      ...geomFirst(a, g, "LatDegree", null),
      spudDate: msToIso(a.SpudDate),
      endDrillDate: msToIso(a.EndedDrill),
      statusDate: msToIso(a.StatusDate),
      depth: nz(a.DrillerTot),
      depthUnit: a.LengthUnit,
      maxTemperature: num(a.MaximumRec),
      temperatureUnit: a.Temperatur,
      headerUrl: a.HeaderURI,
    }),
  },
  {
    key: "WA-OG",
    state: "WA",
    label: "Washington oil & gas wells",
    probe: { operator: "Duncan" },
    agency: "Washington DNR (Geology)",
    url: "https://gis.dnr.wa.gov/site1/rest/services/Public_Geology/Oil_and_Gas_Wells/MapServer/1",
    pageMax: 2000,
    searchFields: {
      api: "API_NUMBER",
      well_name: "WELL_NAME",
      operator: "COMPANY_NAME",
      county: "COUNTY",
      status: "WELL_STATUS",
    },
    normalize: (a, g) => ({
      api: a.API_NUMBER?.replace(/^0(\d{2})-/, "$1-") ?? null, // stored with a 3-digit '046' state code
      wellName: a.WELL_NAME,
      operator: a.COMPANY_NAME,
      status: a.WELL_STATUS,
      wellType: null,
      county: a.COUNTY,
      ...geomFirst(a, g, "LATITUDE", "LONGITUDE"),
      spudDate: msToIso(a.DRILL_START_DATE),
      endDrillDate: msToIso(a.DRILL_STOP_DATE),
      permitDate: msToIso(a.PERMIT_DATE),
      depthMD: nz(a.DEPTH_FEET),
      hydrocarbonShow: a.HYDROCARBON_SHOW,
    }),
  },
  {
    key: "WA-GEO",
    state: "WA",
    label: "Washington geothermal well permits",
    probe: { operator: "Natural Resources" },
    agency: "Washington DNR (Geology)",
    url: "https://gis.dnr.wa.gov/site1/rest/services/Public_Geology/Geothermal/MapServer/4",
    pageMax: 2000,
    idKind: "id",
    idLabel: "geothermal permit number",
    searchFields: {
      api: "PERMIT_NUMBER",
      well_name: "WELL_NAME",
      operator: "PERMIT_HOLDER",
      county: "COUNTY_NAME",
      status: "PERMIT_STATUS",
    },
    normalize: (a, g) => ({
      api: a.PERMIT_NUMBER,
      wellName: a.WELL_NAME,
      operator: a.PERMIT_HOLDER,
      status: a.PERMIT_STATUS,
      wellType: "Geothermal",
      county: a.COUNTY_NAME,
      ...geomFirst(a, g, "LATITUDE", "LONGITUDE"),
      permitDate: msToIso(a.PERMIT_DATE),
      depthFt: nz(a.DRILLED_DEPTH_FEET),
      permittedDepthFt: nz(a.PERMIT_DEPTH_FEET),
    }),
  },
  {
    key: "AZ",
    state: "AZ",
    label: "Arizona oil, gas, helium & geothermal wells",
    probe: { operator: "Ranger" },
    agency: "Arizona Oil & Gas Conservation Commission (hosted by ADEQ)",
    url: "https://utility.arcgis.com/usrsvcs/servers/6c01eae404a44e95a9aad050effe93cd/rest/services/OIL_AND_GAS_WELLS_AGOL/FeatureServer/0",
    pageMax: 2000,
    caveat: "Includes geothermal, helium, CO2 and gas-storage wells. A few historic spud dates carry century errors (they appear as future dates).",
    searchFields: {
      api: "API",
      well_name: "WELL_NAME",
      operator: "OPERATOR",
      county: "COUNTY",
      field: "WELL_FIELD",
      status: "STATUS_WELL",
      well_type: "WELL_TYPE",
    },
    normalize: (a, g) => ({
      api: a.API,
      wellName: a.WELL_NAME || a.LEASE_NAME,
      operator: a.OPERATOR,
      status: a.STATUS_WELL,
      wellType: a.WELL_TYPE,
      field: a.WELL_FIELD,
      county: a.COUNTY,
      ...geomFirst(a, g, "LATITUDE", "LONGITUDE"),
      spudDate: msToIso(a.SPUD_DATE),
      endDrillDate: msToIso(a.DRILL_END_DATE),
      depth: nz(a.DEPTH_DRILL),
      depthUnit: a.DEPTH_UNIT,
      commodity: a.COMMODITY,
      formation: a.FORMATION,
      permit: a.PERMIT,
      detailUrl: a.WEBSITE,
    }),
  },
  {
    key: "NV-GEO",
    state: "NV",
    label: "Nevada geothermal wells",
    probe: { operator: "Ormat" },
    agency: "NBMG (UNR) / NGDS",
    url: "https://gisweb.unr.edu/nbmg/rest/services/MineralsAndEnergy/GeothermalWells/MapServer/0",
    pageMax: 1000,
    searchFields: {
      api: "apino",
      well_name: "wellname",
      operator: "operator_",
      county: "county",
      status: "status",
      well_type: "welltype",
    },
    normalize: (a, g) => ({
      api: a.apino,
      wellName: a.wellname,
      operator: a.operator_,
      status: a.status,
      wellType: a.welltype,
      field: null,
      county: a.county,
      latitude: coord(a, "latdegree", g, "y"),
      longitude: coord(a, "longdegree", g, "x"),
      spudDate: msToIso(a.spuddatetime),
      thermalClass: a.thermalclass,
      permitNo: a.permitno,
    }),
  },
  {
    key: "NV-OG",
    state: "NV",
    label: "Nevada oil & gas wells (compiled through 2013)",
    probe: { operator: "Foreland" },
    agency: "NBMG (UNR)",
    url: "https://gisweb.unr.edu/nbmg/rest/services/MineralsAndEnergy/OilAndGas/MapServer/1",
    pageMax: 1000,
    caveat: "NBMG compilation through 2013: no wells drilled since, and no dates.",
    searchFields: {
      api: "API",
      well_name: "WELL",
      operator: "OPERATOR",
      county: "COUNTY",
      field: "OIL_FIELD",
      status: "STATUS",
    },
    normalize: (a, g) => ({
      api: a.API,
      wellName: a.WELL,
      operator: a.OPERATOR,
      status: a.STATUS,
      wellType: null,
      field: a.OIL_FIELD,
      county: a.COUNTY,
      ...geomFirst(a, g),
      depthMD: nz(a.TD),
      show: a.SHOW,
      logs: a.LOGS,
      samples: a.SAMPLES,
    }),
  },
  {
    key: "AK",
    state: "AK",
    label: "Alaska oil, gas & geothermal wells (incl. state offshore)",
    probe: { operator: "Hilcorp" },
    agency: "Alaska Oil and Gas Conservation Commission (via Alaska Division of Oil & Gas)",
    url: "https://services1.arcgis.com/7HDiw78fcUiM2BWn/arcgis/rest/services/Well_Surface_Hole_Location/FeatureServer/0",
    pageMax: 2000,
    caveat: "Includes a few exploratory geothermal wells (field '*EXPLORATORY, GEOTHERMAL'). Depths in feet.",
    searchFields: {
      api: "APINumber",
      well_name: "WellName",
      operator: "Operator",
      county: "GeographicArea",
      field: "Field",
      status: "CurrentStatus",
      well_type: "CurrentClass",
    },
    normalize: (a, g) => ({
      api: a.APINumber,
      wellName: a.WellName,
      operator: a.Operator,
      status: a.CurrentStatus,
      wellType: a.CurrentClass,
      field: a.Field,
      county: a.GeographicArea,
      ...geomFirst(a, g, "WellHeadLat", "WellHeadLong"),
      spudDate: msToIso(a.SpudDate),
      completionDate: msToIso(a.CompletionDate),
      permitDate: msToIso(a.PermitIssuedDate),
      statusDate: msToIso(a.LastStatusChange),
      depthMD: nz(a.DrillerTotalDepth),
      depthTVD: nz(a.TrueVerticalDepth),
      pools: a.Pools,
      offshore: a.IsWellHeadOffShore,
      permitNumber: a.PermitNumber,
      confidential: a.WellConfidential,
    }),
  },
  {
    key: "HI-GEO",
    state: "HI",
    label: "Hawaii geothermal wells (Puna)",
    probe: { well_name: "KS-" },
    agency: "Hawaii Statewide GIS Program",
    url: "https://geodata.hawaii.gov/arcgis/rest/services/Infrastructure/MapServer/20",
    pageMax: 1000,
    idKind: "id",
    idLabel: "well name",
    caveat: "Puna geothermal field wells only. The State GIS stores each well as a buffer polygon, so coordinates are polygon centroids (approximate); only name and use are published.",
    searchFields: {
      api: "well_name",
      well_name: "well_name",
      well_type: "use",
    },
    normalize: (a, g) => {
      const c = centroid(g);
      return {
        api: a.well_name,
        wellName: a.well_name,
        operator: null,
        status: null,
        wellType: a.use,
        latitude: c?.y ?? null,
        longitude: c?.x ?? null,
      };
    },
  },
  {
    key: "SD",
    state: "SD",
    label: "South Dakota oil & gas wells",
    probe: { operator: "Continental" },
    agency: "South Dakota Geological Survey / DANR",
    url: "https://gis.usd.edu/arcgis/rest/services/SDGS_Interactive_Data_Map/MapServer/9",
    pageMax: 2000,
    searchFields: {
      api: "API_Number",
      well_name: "Well_Name",
      operator: "Operator",
      county: "County",
      status: "Well_AdminStatus",
      well_type: "Well_Type_Current",
    },
    normalize: (a, g) => ({
      api: a.API_Number,
      wellName: a.Well_Name,
      operator: a.Operator,
      status: a.Well_AdminStatus,
      wellType: a.Well_Type_Current,
      county: a.County,
      ...geomFirst(a, g, "lat", "long"),
      spudDate: msToIso(a.Date_Spud),
      plugDate: msToIso(a.Date_plug),
      permitDate: msToIso(a.Date_Issued),
      bottomFormation: a.Bottom_Hole_Formation,
      wellFileUrl: a.Scanned_Well_File_URL,
      recordUrl: a.DatabaseRecord_URL,
      productionUrl: a.Production_URL,
    }),
  },
  {
    key: "ND",
    state: "ND",
    label: "North Dakota oil & gas wells",
    probe: { operator: "Continental" },
    agency: "ND DMR Oil & Gas Division",
    // The OilGasPublicMapDataVectorTiles service began demanding a token in Oct 2026;
    // All_Wells is the keyless MapServer twin with the identical schema (verified 2026-10-06).
    url: "https://gis.dmr.nd.gov/dmrpublicservices/rest/services/All_Wells/MapServer/0",
    pageMax: 2000,
    searchFields: {
      api: "api_no",
      well_name: "well_name",
      operator: "operator",
      county: "County",
      field: "field_name",
      status: "status",
      well_type: "well_type",
    },
    normalize: (a, g) => ({
      api: a.api_no ?? a.api,
      wellName: a.well_name,
      operator: a.operator,
      status: a.status,
      wellType: a.well_type,
      field: a.field_name,
      county: a.County,
      latitude: coord(a, "latitude", g, "y"),
      longitude: coord(a, "longitude", g, "x"),
      spudDate: msToIso(a.spud_date),
      depthMD: a.td,
      ndicFileNo: a.fileno,
    }),
  },

  // ------------------------------------------------------------ Texas
  {
    key: "TX",
    state: "TX",
    label: "Texas well locations (location + API only)",
    probe: { api: "42130441" },
    agency: "Texas RRC public GIS",
    url: "https://gis.rrc.texas.gov/server/rest/services/rrc_public/RRC_Public_Viewer_Srvs/MapServer/1",
    pageMax: 1000,
    searchFields: {
      api: "API",
      well_name: "GIS_WELL_NUMBER",
    },
    caveat:
      "TX RRC GIS carries only API number, well number, symbol and coordinates. For operator, lease, field and county use TX-RRC (same wells, RRC's wellbore query).",
    normalize: (a, g) => ({
      api: a.API,
      wellName: a.GIS_WELL_NUMBER,
      operator: null,
      status: null,
      wellType: a.GIS_SYMBOL_DESCRIPTION,
      field: null,
      county: null,
      latitude: coord(a, "GIS_LAT83", g, "y"),
      longitude: coord(a, "GIS_LONG83", g, "x"),
      spudDate: null,
    }),
  },
  {
    key: "TX-RRC",
    state: "TX",
    kind: "rrc-ewa",
    label: "Texas wellbores with operator, lease, field and county",
    probe: { operator: "Merit Energy" },
    agency: "Texas Railroad Commission (EWA wellbore query)",
    url: "https://webapps2.rrc.texas.gov/EWA/wellboreQueryAction.do (CSV export)",
    pageMax: 500,
    noNear: true, // no coordinates of its own; wells_near uses TX
    requiresOneOf: ["operator", "api", "county"],
    caveat:
      "One row per wellbore and lease. Needs operator, api or county (RRC has no statewide name search); lease and field names filter within those results. status/well_type take one RRC code name (PRODUCING, SHUT IN, INJECTION, TEMP ABANDONED, GEOTHERMAL WELL...). Coordinates are joined from the TX GIS layer. No dates.",
    searchFields: {
      api: "API No.",
      operator: "Operator Name",
      county: "County",
      well_name: "Lease Name",
      field: "Field Name",
      status: "Well Type",
      well_type: "Well Type",
    },
    normalize: (a, g) => {
      const api8 = String(a["API No."] ?? "").padStart(8, "0");
      return {
        api: `42-${api8.slice(0, 3)}-${api8.slice(3)}`,
        wellName: joinName(a["Lease Name"], a["Well No."]),
        operator: a["Operator Name"],
        status: a._rrcWellType ?? null,
        wellType: null,
        field: a["Field Name"],
        county: a.County,
        latitude: g?.y ?? null,
        longitude: g?.x ?? null,
        district: a.District,
        leaseNumber: a["Lease No."],
        onSchedule: a["On Schedule"],
        apiDepthFt: nz(a["API Depth"]),
      };
    },
  },

  // ------------------------------------------------------- Mid-Continent
  {
    key: "OK",
    state: "OK",
    label: "Oklahoma oil, gas & injection wells",
    probe: { operator: "Devon" },
    agency: "Oklahoma Corporation Commission (RBDMS)",
    url: "https://gis.occ.ok.gov/server/rest/services/Hosted/RBDMS_WELLS/FeatureServer/2",
    pageMax: 2000,
    apiNumeric: true,
    caveat: "No field, dates or depth in OCC's GIS layer; each record links to its well-records documents.",
    searchFields: {
      api: "api",
      well_name: "well_name",
      operator: "operator",
      county: "county",
      status: "wellstatus",
      well_type: "welltype",
    },
    normalize: (a, g) => ({
      api: a.api != null ? String(a.api) : null,
      wellName: joinName(a.well_name, a.well_num),
      operator: a.operator,
      status: a.wellstatus,
      wellType: a.welltype,
      county: a.county,
      ...geomFirst(a, g, "sh_lat", "sh_lon"),
      documentsUrl: a.well_records_docs,
    }),
  },
  {
    key: "KS",
    state: "KS",
    label: "Kansas oil & gas wells",
    probe: { operator: "Oxy" },
    agency: "Kansas Geological Survey (KCC well data)",
    url: "https://services2.arcgis.com/ZOdjAzAQ2B0f85zi/arcgis/rest/services/Oil_and_Gas_Wells/FeatureServer/0",
    pageMax: 2000,
    caveat: "The operator filter matches the original operator; operator in results shows the current operator when KGS has one.",
    searchFields: {
      api: "API_NUMBER",
      well_name: "LEASE_NAME",
      operator: "OPERATOR_NAME",
      county: "COUNTY",
      field: "FIELD_NAME",
      status: "STATUS",
      well_type: "WELL_CLASS",
    },
    normalize: (a, g) => ({
      api: a.API_NUMBER,
      wellName: joinName(a.LEASE_NAME, a.WELL_NAME),
      operator: a.CURR_OPERATOR || a.OPERATOR_NAME,
      originalOperator: a.OPERATOR_NAME,
      status: a.STATUS,
      wellType: a.WELL_CLASS || a.WELL_TYPE,
      field: a.FIELD_NAME,
      county: a.COUNTY,
      ...geomFirst(a, g), // NAD27_* attributes are NAD27
      spudDate: msToIso(a.SPUD_DATE),
      permitDate: msToIso(a.PERMIT_DATE),
      completionDate: msToIso(a.COMPLETION_DATE),
      plugDate: msToIso(a.PLUG_DATE),
      depthMD: nz(a.ROTARY_TOTAL_DEPTH),
      producingFormation: a.PRODUCING_FORMATION,
      ipOil: num(a.IP_OIL),
      ipGas: num(a.IP_GAS),
      ipWater: num(a.IP_WATER),
      kgsId: a.KID,
    }),
  },
  {
    key: "NE",
    state: "NE",
    kind: "wfs",
    label: "Nebraska oil & gas wells (API, name, location)",
    probe: { well_name: "Meyer" },
    agency: "Nebraska Oil & Gas Conservation Commission",
    url: "http://www.nogcc.ne.gov:8080/geoserver/wfs", // the server offers no HTTPS
    typeName: "NOGCC:NEWells",
    geometryName: "the_geom",
    sortBy: "API_WellNo",
    pageMax: 2000,
    caveat: "Only API number, well name and location are published as data; operator, status and dates are not.",
    searchFields: {
      api: "API_WellNo",
      well_name: "Well_Name",
    },
    normalize: (a, g) => ({
      api: a.API_WellNo,
      wellName: a.Well_Name,
      operator: null,
      status: null,
      wellType: null,
      ...geomFirst(a, g, "Y", "X"),
    }),
  },
  {
    key: "MO",
    state: "MO",
    label: "Missouri oil & gas wells",
    probe: { operator: "Carmel" },
    agency: "Missouri DNR / Missouri Geological Survey",
    url: "https://gis.dnr.mo.gov/host/rest/services/geology/oil_gas_wells/MapServer/0",
    pageMax: 2000,
    searchFields: {
      api: "API_NUMBER",
      well_name: "LEASE",
      operator: "OPERATOR",
      county: "COUNTY",
      field: "FIELD_POOL",
      status: "STATUS",
      well_type: "WELL_TYPE",
    },
    normalize: (a, g) => ({
      api: a.API_NUMBER ? `24-${a.API_NUMBER}` : null, // layer omits the 24 state prefix
      wellName: joinName(a.LEASE, a.WELL_NAME),
      operator: a.OPERATOR,
      status: a.STATUS,
      wellType: a.WELL_TYPE,
      field: a.FIELD_POOL,
      county: a.COUNTY,
      ...geomFirst(a, g, "LATITUDE", "LONGITUDE"),
      spudDate: msToIso(a.SPUD_DATE),
      permitDate: msToIso(a.PERMIT_DAT),
      statusDate: msToIso(a.STATUSDATE),
      depthMD: nz(a.TOTAL_DPTH),
      formation: a.FORMATION,
      permitUrl: a.PERMIT_LINK,
    }),
  },
  {
    key: "AR",
    state: "AR",
    label: "Arkansas oil & gas wells",
    probe: { operator: "Flywheel" },
    agency: "Arkansas Oil and Gas Commission (via Arkansas GIS Office)",
    url: "https://gis.arkansas.gov/arcgis/rest/services/FEATURESERVICES/Utilities/FeatureServer/5",
    pageMax: 500,
    dedupeBy: "wellid", // the layer repeats rows per well
    caveat: "Dry holes are largely missing from this layer.",
    searchFields: {
      api: "wellid",
      well_name: "wellname",
      operator: "operatorname",
      county: "countyname",
      field: "fieldname",
      status: "wellstatusdescription",
      well_type: "welltypedescription",
    },
    normalize: (a, g) => ({
      api: a.wellid ? `0${a.wellid}` : null, // stored without the leading 0 of state code 03
      wellName: joinName(a.wellname, a.wellnumber),
      operator: a.operatorname,
      status: a.wellstatusdescription,
      wellType: a.welltypedescription,
      field: a.fieldname,
      county: a.countyname,
      ...geomFirst(a, g, "coordinates_latitude", "coordinates_longitude"),
      statusDate: usDateToIso(a.wellstatusdate),
      depthMD: nz(a.depthbottom),
      pool: a.poolnamestring,
      permit: a.permitnumberstring,
    }),
  },

  // ---------------------------------------------------------- Gulf Coast
  {
    key: "LA",
    state: "LA",
    label: "Louisiana oil & gas wells (incl. state waters)",
    probe: { operator: "Denbury" },
    agency: "Louisiana DENR Office of Conservation (SONRIS)",
    url: "https://sonris-gis.dnr.la.gov/arcgis/rest/services/DNRSvc/OC/MapServer/0",
    pageMax: 1000,
    // '*' would pull a blob column and long text; ask for what the normalizer uses.
    outFields:
      "WELL_SERIAL_NUM,API_NUM,WELL_NAME,WELL_NUM,ORG_OPER_NAME,WELL_STATUS_CODE,LEGEND_DESC,PRODUCT_TYPE_CODE,WELL_CLASS_TYPE_CODE,FIELD_NAME,PARISH_NAME,SURFACE_LAT_DEC_DEG,SURFACE_LONG_DEC_DEG,PERMIT_DATE,SPUD_DATE,ORIGINAL_COMPLETION_DATE,WELL_STATUS_DATE,MEASURED_DEPTH,TRUE_VERTICAL_DEPTH,SANDS,FORMATIONS,HYPERLINK,LEASE_NUM",
    caveat: "Some old wells carry API '00000000000000'; their serialNumber is the reliable key.",
    searchFields: {
      api: "API_NUM",
      well_name: "WELL_NAME",
      operator: "ORG_OPER_NAME",
      county: "PARISH_NAME",
      field: "FIELD_NAME",
      status: "LEGEND_DESC",
      well_type: "WELL_CLASS_TYPE_CODE",
    },
    normalize: (a, g) => ({
      api: a.API_NUM && !/^0+$/.test(a.API_NUM) ? a.API_NUM : null,
      serialNumber: a.WELL_SERIAL_NUM,
      wellName: joinName(a.WELL_NAME, a.WELL_NUM),
      operator: a.ORG_OPER_NAME,
      status: a.LEGEND_DESC?.replace(/\s+/g, " ") || a.WELL_STATUS_CODE,
      statusCode: a.WELL_STATUS_CODE,
      wellType: a.WELL_CLASS_TYPE_CODE,
      productType: a.PRODUCT_TYPE_CODE,
      field: a.FIELD_NAME,
      county: a.PARISH_NAME,
      ...geomFirst(a, g, "SURFACE_LAT_DEC_DEG", "SURFACE_LONG_DEC_DEG"),
      permitDate: msToIso(a.PERMIT_DATE),
      spudDate: msToIso(a.SPUD_DATE),
      completionDate: msToIso(a.ORIGINAL_COMPLETION_DATE),
      statusDate: msToIso(a.WELL_STATUS_DATE),
      depthMD: nz(a.MEASURED_DEPTH),
      depthTVD: nz(a.TRUE_VERTICAL_DEPTH),
      sands: a.SANDS,
      formations: a.FORMATIONS,
      detailUrl: a.HYPERLINK,
    }),
  },
  {
    key: "MS",
    state: "MS",
    kind: "wfs",
    label: "Mississippi oil & gas wells",
    probe: { field: "Mantua" },
    agency: "Mississippi State Oil & Gas Board",
    url: "https://ws.ogb.state.ms.us/geoserver/wfs",
    typeName: "Heatmap:wells_otherfields",
    geometryName: "the_geom",
    sortBy: "PKey",
    pageMax: 2000,
    caveat: "No operator or spud date in the published layer.",
    searchFields: {
      api: "API",
      well_name: "DispName",
      county: "CountyName",
      field: "FieldName",
      status: "statdesc",
      well_type: "typedesc",
    },
    normalize: (a, g) => ({
      api: a.API,
      wellName: a.DispName,
      operator: null,
      status: a.statdesc,
      wellType: a.typedesc,
      field: a.FieldName,
      county: a.CountyName,
      latitude: g?.y ?? null,
      longitude: g?.x ?? null,
      permitDate: isoDate(a.PermitDate),
      depthMD: nz(a.TD),
    }),
  },
  {
    key: "AL",
    state: "AL",
    label: "Alabama oil, gas & coalbed-methane wells",
    probe: { operator: "Exxon" },
    agency: "State Oil and Gas Board of Alabama (via Geological Survey of Alabama)",
    url: "https://gis.gsa.state.al.us/arcgis/rest/services/OGB/OGBOnlineMap/MapServer/0",
    pageMax: 2000,
    license:
      "OGB terms (gsa.state.al.us/img/ogb/gis_constraints.txt) forbid redistributing the data to third parties without OGB permission: query it live, don't republish it.",
    searchFields: {
      api: "API",
      well_name: "WellName",
      operator: "Operator",
      county: "CountyName",
      field: "FieldName",
      status: "StatusDesc",
      well_type: "TypeDesc",
    },
    normalize: (a, g) => ({
      api: a.API,
      wellName: a.WellName,
      operator: a.Operator,
      status: a.StatusDesc ?? a.WellStatus,
      wellType: a.TypeDesc ?? a.WellType,
      field: a.FieldName,
      county: a.CountyName,
      ...geomFirst(a, g), // Latitude/Longitude attributes are NAD27
      permitDate: msToIso(a.PermitDate),
      spudDate: msToIso(a.SpudDate),
      firstProductionDate: msToIso(a.FirstProductionDate),
      statusDate: msToIso(a.StatusDate),
      depthMD: nz(a.MD) ?? nz(a.DTD),
      depthTVD: nz(a.TVD),
      pool: a.PoolName,
      permit: a.Permit,
    }),
  },

  // ------------------------------------------------- Appalachia / Midwest
  {
    key: "PA",
    state: "PA",
    label: "Pennsylvania oil & gas wells",
    probe: { operator: "EQT" },
    agency: "Pennsylvania DEP Office of Oil and Gas Management",
    url: "https://gis.dep.pa.gov/depgisprd/rest/services/OilGas_Collector/OG_Layers_OG_Well_Data/MapServer/0",
    pageMax: 1000,
    caveat: "No depth or formation values (the fields exist but are blank).",
    searchFields: {
      api: "PERMIT_NUMBER",
      well_name: "WELL_NAME",
      operator: "OPERATOR",
      county: "COUNTY",
      status: "WELL_STATUS",
      well_type: "WELL_TYPE",
    },
    normalize: (a, g) => ({
      api: a.PERMIT_NUMBER ? `37-${a.PERMIT_NUMBER}` : null, // permit number = API without the 37 prefix
      wellName: a.WELL_NAME,
      operator: a.OPERATOR,
      status: a.WELL_STATUS,
      wellType: a.WELL_TYPE,
      county: a.COUNTY,
      municipality: a.MUNICIPALITY,
      ...geomFirst(a, g, "LATITUDE", "LONGITUDE"),
      permitDate: msToIso(a.PERMIT_DATE),
      spudDate: msToIso(a.SPUD_DATE),
      plugDate: msToIso(a.DATE_PLUGGED),
      unconventional: a.UNCONVENTIONAL_IND,
      configuration: a.WELL_CONFIG_CODE,
      padName: a.WELL_PAD_NAME,
      storageField: a.STORAGE_FIELD_NAME,
    }),
  },
  {
    key: "OH",
    state: "OH",
    label: "Ohio oil & gas wells",
    probe: { operator: "Ascent" },
    agency: "Ohio DNR Division of Oil & Gas Resources",
    url: "https://services5.arcgis.com/ajRlmtxbNBjZggOT/arcgis/rest/services/Oil_And_Gas_Wells/FeatureServer/3",
    pageMax: 2000,
    searchFields: {
      api: "API_NO",
      well_name: "WELL_NAME",
      operator: "COMPANY_NAME",
      county: "COUNTY",
      status: "WELL_STATUS_DESCRIPTION",
      well_type: "WELL_TYP",
    },
    normalize: (a, g) => ({
      api: a.API_NO,
      wellName: joinName(a.WELL_NAME, a.WELL_NO),
      leaseName: a.LEASE_NAME,
      operator: a.COMPANY_NAME,
      status: a.WELL_STATUS_DESCRIPTION,
      wellType: a.WELL_TYP,
      county: a.COUNTY,
      township: a.TOWNSHIP,
      ...geomFirst(a, g, "LAT83", "LONG83"),
      permitDate: msToIso(a.PERMIT_ISSUED_DATE),
      completionDate: msToIso(a.COMP_DATE),
      plugDate: msToIso(a.PLUG_DATE),
      depthMD: nz(a.TOTAL_DEPTH),
      producingFormation: a.PRODFM1,
      deepestFormation: a.DEEPEST_FORMATION,
      slant: a.SLANT,
      ipOil: num(a.IP_OIL),
      ipGas: num(a.IP_GAS),
      lastProductionYear: a.Last_Nonzero_Production_Year,
      documentsUrl: a.PDF_LINK,
    }),
  },
  {
    key: "WV",
    state: "WV",
    label: "West Virginia oil & gas wells",
    probe: { operator: "EQT" },
    agency: "West Virginia DEP Office of Oil and Gas",
    url: "https://tagis.dep.wv.gov/arcgis/rest/services/WVDEP_enterprise/oil_gas/MapServer/7",
    pageMax: 2000,
    caveat: "issueDate/completionDate belong to the latest permit action on the well, which may be a plugging permit. depthClass is a category, not a number.",
    searchFields: {
      api: "api",
      well_name: "farmname",
      operator: "respparty",
      county: "county",
      status: "wellstatus",
      well_type: "welltype",
    },
    normalize: (a, g) => ({
      api: a.api,
      wellName: joinName(a.farmname, a.wellnumber),
      operator: a.respparty,
      status: a.wellstatus,
      wellType: a.welltype,
      wellUse: a.welluse,
      county: a.county,
      ...geomFirst(a, g),
      issueDate: isoDate(a.issuedate),
      completionDate: isoDate(a.compdate),
      depthClass: a.welldepth,
      formation: a.formation,
      marcellus: a.marcellus,
      permit: a.permitid,
      detailUrl: a.link,
    }),
  },
  {
    key: "KY",
    state: "KY",
    label: "Kentucky oil & gas wells",
    probe: { operator: "Equitable" },
    agency: "Kentucky Geological Survey",
    url: "https://kgs.uky.edu/arcgis/rest/services/KYOilGas/KYOilGasWells_SZ_OneLayer/MapServer/0",
    pageMax: 2000,
    baseWhere: "bogus_location = 0", // ~32k records sit at 0,0
    caveat: "About a quarter of records have no API number; recordNumber is KGS's key for those. Records without a valid location are excluded.",
    searchFields: {
      api: "API_Number",
      well_name: "farm_name",
      operator: "operator",
      county: "county_name",
      field: "pool_name",
      status: "original_result",
    },
    normalize: (a, g) => ({
      api: a.API_Number,
      recordNumber: a.record_number,
      wellName: joinName(a.farm_name, a.well_number),
      operator: a.most_recent_operator || a.operator,
      originalOperator: a.operator,
      status: a.original_result,
      plugged: a.plugged === 1 ? true : a.plugged === 0 ? false : null,
      field: a.pool_name,
      county: a.county_name,
      ...geomFirst(a, g, "north_latitude83", null), // west_longitude83 is west-positive
      spudDate: msToIso(a.date_spudded),
      completionDate: msToIso(a.date_completed),
      plugDate: msToIso(a.date_plugged),
      permitDate: msToIso(a.date_permit_issued),
      depthMD: nz(a.total_depth),
      depthTVD: nz(a.true_vertical_depth),
      tdFormation: a.tdfm_name,
      deepestPay: a.deepest_pay_name,
    }),
  },
  {
    key: "IL",
    state: "IL",
    label: "Illinois oil & gas wells",
    probe: { operator: "Citation" },
    agency: "Illinois State Geological Survey (ILOIL)",
    url: "https://maps.isgs.illinois.edu/arcgis/rest/services/ILOIL/Wells/MapServer/8",
    pageMax: 2000,
    caveat: "No county or field name fields; no spud date.",
    searchFields: {
      api: "API_NUMBER",
      well_name: "FARM_NAME",
      operator: "COMPANY_NAME",
      status: "STATUS_TEXT",
    },
    normalize: (a, g) => ({
      api: a.API_NUMBER,
      wellName: joinName(a.FARM_NAME, a.FARM_NUM),
      operator: a.COMPANY_NAME,
      status: a.STATUS_TEXT || a.STATUS,
      ...geomFirst(a, g, "LATITUDE", "LONGITUDE"),
      completionDate: msToIso(a.COMP_DATE),
      permitDate: msToIso(a.PERMIT_DATE),
      depthMD: nz(a.TOTAL_DEPTH),
      tdFormation: a.TDFMTEXT,
      summaryUrl: a.DataSummary,
    }),
  },
  {
    key: "IN",
    state: "IN",
    label: "Indiana oil & gas wells",
    probe: { operator: "Countrymark" },
    agency: "Indiana DNR Division of Oil & Gas",
    url: "https://services.arcgis.com/2Mcx1M1MORKfBNPM/arcgis/rest/services/OilAndGasWells/FeatureServer/0",
    pageMax: 2000,
    idKind: "id",
    idLabel: "Indiana permit number",
    caveat: "No API number, well type, dates or depth in this layer.",
    searchFields: {
      api: "permit_number",
      well_name: "lease_name",
      operator: "operator_name",
      county: "county",
      status: "status",
    },
    normalize: (a, g) => ({
      api: a.permit_number,
      wellName: joinName(a.lease_name, a.well_number),
      operator: a.operator_name,
      status: a.status,
      county: a.county,
      ...geomFirst(a, g),
      igsId: a.igs_id,
      classII: a.classii,
      hydrofrac: a.hydrofrac,
    }),
  },
  {
    key: "MI",
    state: "MI",
    label: "Michigan oil, gas & mineral wells",
    probe: { operator: "Riverside" },
    agency: "Michigan EGLE (Oil, Gas, and Minerals Division)",
    url: "https://gisagoegle.state.mi.us/arcgis/rest/services/EGLE/GrmdOpenData/MapServer/10",
    pageMax: 2000,
    caveat: "Includes mineral (Part 625) wells; filter well_type for oil & gas. No spud or completion date.",
    searchFields: {
      api: "api_num",
      well_name: "WellNameFull",
      operator: "CompanyName",
      county: "CountyName",
      field: "FieldName",
      status: "WellStatus",
      well_type: "WellType",
    },
    normalize: (a, g) => ({
      api: a.api_num,
      wellName: a.WellNameFull,
      operator: a.CompanyName,
      status: a.WellStatus,
      wellType: a.WellType,
      field: a.FieldName,
      county: a.CountyName,
      ...geomFirst(a, g, "Y", "X"),
      permitDate: msToIso(a.PermitDate),
      plugDate: msToIso(a.PluggingDate),
      depthMD: nz(a.DTD),
      depthTVD: nz(a.TVD),
      producingFormation: a.ProducingFormation,
      slant: a.Slant,
    }),
  },
  {
    key: "NY",
    state: "NY",
    label: "New York oil, gas & solution-mining wells",
    probe: { operator: "Greenway" },
    agency: "New York DEC Division of Mineral Resources",
    url: "https://gisservices.dec.ny.gov/arcgis/rest/services/mines_and_wells/MapServer/1",
    pageMax: 1000,
    searchFields: {
      api: "API_WELLNO",
      well_name: "WELL_NAME",
      operator: "COMPANY_NAME",
      county: "COUNTY",
      field: "PRODUCING_NAME",
      status: "WELL_STATUS",
      well_type: "WELL_TYPE",
    },
    normalize: (a, g) => ({
      api: a.API_WELLNO,
      wellName: a.WELL_NAME,
      operator: a.COMPANY_NAME,
      status: a.WELL_STATUS,
      generalStatus: a.GENERALWELLSTATUS,
      wellType: a.WELL_TYPE,
      generalType: a.GENERALWELLTYPE,
      field: a.PRODUCING_NAME,
      county: a.COUNTY,
      ...geomFirst(a, g, "SURFACE_LATITUDE", "SURFACE_LONGITUDE"),
      permitDate: msToIso(a.PERMIT_ISSUED),
      spudDate: msToIso(a.DATE_SPUDDED),
      completionDate: msToIso(a.DATE_WELL_COMPLETED),
      plugDate: msToIso(a.DATE_WELL_PLUGGED),
      depthMD: nz(a.MEASURED_DEPTH),
      depthTVD: nz(a.TRUE_VERTICAL_DEPTH),
      producingFormation: a.PRODUCING_FORMATION,
      detailUrl: a.LINK,
    }),
  },
  {
    key: "TN",
    state: "TN",
    label: "Tennessee oil & gas wells",
    probe: { operator: "Diversified" },
    agency: "Tennessee Department of Environment and Conservation (TDEC)",
    url: "https://tdeconline.tn.gov/arcgis/rest/services/Oil_and_Gas2/MapServer/0",
    pageMax: 2000,
    // TDEC's server answers 403 unless the User-Agent looks like a browser.
    headers: { "User-Agent": `Mozilla/5.0 (compatible; ${USER_AGENT}; +https://github.com/Wickemu/well-data-mcp)` },
    caveat: "Status and purpose are one combined field. No spud date or depth.",
    searchFields: {
      api: "API_NO",
      well_name: "WELL_NAME_AND_NO",
      operator: "OPERATOR_NAME",
      county: "COUNTY",
      status: "PURPOSE_OF_WELL",
    },
    normalize: (a, g) => ({
      api: a.API_NO ? `41-${a.API_NO}` : null, // layer omits the 41 state prefix
      wellName: a.WELL_NAME_AND_NO,
      operator: a.OPERATOR_NAME,
      status: a.PURPOSE_OF_WELL,
      county: a.COUNTY,
      ...geomFirst(a, g, "LATITUDE", "LONGITUDE"),
      permitDate: msToIso(a.PERMIT_DATE),
      permit: a.PERMIT_NO,
      tdFormation: a.FORMATION_AT_TOTAL_DEPTH,
    }),
  },
  {
    key: "VA",
    state: "VA",
    label: "Virginia gas & oil wells (active)",
    probe: { operator: "Diversified" },
    agency: "Virginia Energy, Division of Gas and Oil",
    url: "https://energy.virginia.gov/gis/rest/services/DGO/DGO_wells/MapServer/0",
    pageMax: 2000,
    idKind: "id",
    idLabel: "DGO file number",
    caveat: "Active wells only (plugged wells are a separate DGO layer); identified by DGO file number, not API.",
    searchFields: {
      api: "FiNo",
      well_name: "FiFarm",
      operator: "CoName",
      county: "TblCnName",
      status: "TblPsDesc",
      well_type: "TblOpDesc",
    },
    normalize: (a, g) => ({
      api: a.FiNo,
      wellName: a.FiFarm,
      operator: a.CoName,
      status: a.TblPsDesc,
      wellType: a.TblOpDesc,
      county: a.TblCnName,
      ...geomFirst(a, g),
      drillCompleteDate: msToIso(a.FiDrComp),
      completionDate: msToIso(a.FiWellComp),
      statusDate: msToIso(a.FiStatDt),
      depthMD: nz(a.TotalDepth),
    }),
  },
];

// Rough state bounding boxes [minLon, minLat, maxLon, maxLat], padded a little and
// including state waters - wells_near only asks sources whose box overlaps the circle.
const STATE_EXTENTS = {
  AK: [[-180, 50.5, -129.5, 71.6], [172, 50.5, 180, 53.5]],
  AL: [-88.6, 30.0, -84.8, 35.1],
  AR: [-94.7, 32.9, -89.6, 36.6],
  AZ: [-114.9, 31.3, -109.0, 37.1],
  CA: [-124.6, 32.4, -114.0, 42.1],
  CO: [-109.1, 36.9, -102.0, 41.1],
  HI: [-160.3, 18.8, -154.7, 22.3],
  ID: [-117.3, 41.9, -111.0, 49.1],
  IL: [-91.6, 36.9, -87.4, 42.6],
  IN: [-88.2, 37.7, -84.7, 41.8],
  KS: [-102.1, 36.9, -94.5, 40.1],
  KY: [-89.6, 36.4, -81.9, 39.2],
  LA: [-94.1, 28.8, -88.7, 33.1],
  MI: [-90.5, 41.6, -82.3, 48.4],
  MO: [-95.8, 35.9, -89.0, 40.7],
  MS: [-91.7, 30.1, -88.0, 35.1],
  MT: [-116.1, 44.3, -104.0, 49.1],
  ND: [-104.1, 45.9, -96.5, 49.1],
  NE: [-104.1, 39.9, -95.3, 43.1],
  NM: [-109.1, 31.3, -103.0, 37.1],
  NV: [-120.1, 34.9, -114.0, 42.1],
  NY: [-79.8, 40.4, -71.8, 45.1],
  OH: [-84.9, 38.4, -80.5, 42.4],
  OK: [-103.1, 33.6, -94.4, 37.1],
  OR: [-124.7, 41.9, -116.4, 46.3],
  PA: [-80.6, 39.7, -74.7, 42.3],
  SD: [-104.1, 42.4, -96.4, 46.0],
  TN: [-90.4, 34.9, -81.6, 36.7],
  TX: [-106.7, 25.8, -93.4, 36.6],
  UT: [-114.1, 36.9, -109.0, 42.1],
  VA: [-83.7, 36.5, -75.2, 39.5],
  WA: [-124.9, 45.5, -116.9, 49.1],
  WV: [-82.7, 37.2, -77.7, 40.7],
  WY: [-111.1, 40.9, -104.0, 45.1],
};

export const US_SOURCES = STATE_SOURCES.map((s) => ({
  country: "US",
  idKind: "us-api",
  extent: STATE_EXTENTS[s.state],
  ...s,
}));
